package com.defano.wyldcard.window.layouts;

import com.defano.wyldcard.WyldCard;
import com.defano.wyldcard.aspect.RunOnDispatch;
import com.defano.wyldcard.window.WyldCardDialog;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

public class IntensityPalette extends WyldCardDialog<Object> {

    private final static IntensityPalette instance = new IntensityPalette();

    private JSlider intensitySlider;
    private JPanel intensityPanel;
    private JCheckBox smooth;

    private IntensityPalette() {
        intensitySlider.setValue((int) (WyldCard.getInstance().getToolsManager().getIntensity() * 100.0));
        intensitySlider.addChangeListener(e -> WyldCard.getInstance().getToolsManager().setIntensity(intensitySlider.getValue() / 100.0));

        smooth.setSelected(WyldCard.getInstance().getToolsManager().getPathInterpolation());
        smooth.addChangeListener(e -> WyldCard.getInstance().getToolsManager().setPathInterpolation(smooth.isSelected()));
    }

    public static IntensityPalette getInstance() {
        return instance;
    }

    @Override
    public JComponent getWindowPanel() {
        return intensityPanel;
    }

    @Override
    @RunOnDispatch
    public void bindModel(Object data) {
        // Nothing to do
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        intensityPanel = new JPanel();
        intensityPanel.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        intensityPanel.setMaximumSize(new Dimension(246, 2147483647));
        intensityPanel.setMinimumSize(new Dimension(246, 96));
        intensitySlider = new JSlider();
        intensitySlider.setInverted(false);
        intensitySlider.setMajorTickSpacing(8);
        intensitySlider.setMaximum(32);
        intensitySlider.setMinimum(0);
        intensitySlider.setMinorTickSpacing(2);
        intensitySlider.setPaintLabels(false);
        intensitySlider.setPaintTicks(true);
        intensitySlider.setValueIsAdjusting(false);
        intensityPanel.add(intensitySlider, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        intensityPanel.add(spacer1, new GridConstraints(1, 1, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        smooth = new JCheckBox();
        smooth.setText("Smooth spray");
        intensityPanel.add(smooth, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        intensityPanel.add(spacer2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return intensityPanel;
    }

}
