package com.defano.wyldcard.window.layouts;

import com.defano.jmonet.canvas.JMonetCanvas;
import com.defano.jmonet.model.PaintToolType;
import com.defano.jmonet.tools.builder.PaintToolBuilder;
import com.defano.wyldcard.patterns.WyldCardPatternFactory;
import com.defano.wyldcard.window.WyldCardDialog;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;

public class PatternEditor extends WyldCardDialog {
    private JPanel windowPanel;
    private JPanel editorPanel;
    private JButton saveButton;
    private JPanel patternPanel;
    private JMonetCanvas patternCanvas;

    public PatternEditor() {
        saveButton.addActionListener(e -> {
            patternCanvas.dispose();
            dispose();
        });
    }

    @Override
    public JComponent getWindowPanel() {
        return windowPanel;
    }

    @Override
    public void bindModel(Object data) {
        final int scale = 32;
        final int previewSize = 80;

        TexturePaint paint = WyldCardPatternFactory.getInstance().getPattern((int) data);
        BufferedImage paintImage = new BufferedImage(WyldCardPatternFactory.PATTERN_WIDTH, WyldCardPatternFactory.PATTERN_HEIGHT, BufferedImage.TYPE_INT_ARGB);
        BufferedImage previewImage = new BufferedImage(previewSize, previewSize, BufferedImage.TYPE_INT_ARGB);

        Graphics2D g = paintImage.createGraphics();
        g.setPaint(paint);
        g.fillRect(0, 0, WyldCardPatternFactory.PATTERN_WIDTH, WyldCardPatternFactory.PATTERN_HEIGHT);
        g.dispose();

        g = previewImage.createGraphics();
        g.setPaint(paint);
        g.fillRect(0, 0, previewSize, previewSize);
        g.dispose();

        JLabel preview = new JLabel();
        ImageIcon previewIcon = new ImageIcon(previewImage);
        preview.setIcon(previewIcon);
        patternPanel.add(preview);

        patternCanvas = new JMonetCanvas(paintImage);
        patternCanvas.setScale(scale);

        PaintToolBuilder.create(PaintToolType.PENCIL)
                .makeActiveOnCanvas(patternCanvas)
                .build();

        editorPanel.setSize(new Dimension(scale * WyldCardPatternFactory.PATTERN_WIDTH, scale * WyldCardPatternFactory.PATTERN_HEIGHT));
        editorPanel.add(patternCanvas);
        editorPanel.invalidate();
    }

    @Override
    public JButton getDefaultButton() {
        return saveButton;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        windowPanel = new JPanel();
        windowPanel.setLayout(new GridLayoutManager(4, 2, new Insets(10, 10, 10, 10), -1, -1));
        editorPanel = new JPanel();
        editorPanel.setLayout(new BorderLayout(0, 0));
        windowPanel.add(editorPanel, new GridConstraints(0, 0, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        editorPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        final Spacer spacer1 = new Spacer();
        windowPanel.add(spacer1, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        patternPanel = new JPanel();
        patternPanel.setLayout(new BorderLayout(0, 0));
        windowPanel.add(patternPanel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        patternPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        saveButton = new JButton();
        saveButton.setText("Save");
        windowPanel.add(saveButton, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        windowPanel.add(spacer2, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        windowPanel.add(spacer3, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return windowPanel;
    }
}
