package com.defano.wyldcard.window.layouts;

import com.defano.jmonet.algo.transform.image.ScaleTransform;
import com.defano.wyldcard.WyldCard;
import com.defano.wyldcard.parts.card.CardPart;
import com.defano.wyldcard.parts.stack.StackPart;
import com.defano.wyldcard.runtime.context.ExecutionContext;
import com.defano.wyldcard.util.LimitedDepthStack;
import com.defano.wyldcard.util.WrapLayout;
import com.defano.wyldcard.window.WyldCardDialog;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.List;

public class RecentsWindow extends WyldCardDialog {
    private JPanel windowPanel;
    private JPanel recentsPanel;
    private ArrayList<CardPart> cards = new ArrayList<>();

    @Override
    public JComponent getWindowPanel() {

        recentsPanel.setLayout(new WrapLayout());
        ((WrapLayout) recentsPanel.getLayout()).setHgap(2);
        ((WrapLayout) recentsPanel.getLayout()).setVgap(2);

        return windowPanel;
    }

    @Override
    public void bindModel(Object focusedStack) {
        LimitedDepthStack<Integer> backstack = ((StackPart) focusedStack).getStackModel().getBackStack();
    }

    private void loadCard(StackPart focusedStack, int cardNumber) {
        CardPart loadedCard = focusedStack.loadCard(new ExecutionContext(), cardNumber);

        SwingUtilities.invokeLater(() -> {
            BufferedImage image = loadedCard.getScreenshot();
            image = new ScaleTransform(new Dimension(160, 120)).apply(image);

            ImageIcon ii = new ImageIcon(image);
            JButton il = new JButton();
            il.setIcon(ii);

            recentsPanel.add(il);
            
            loadedCard.dispose();
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        windowPanel = new JPanel();
        windowPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        windowPanel.setMinimumSize(new Dimension(300, 250));
        final JScrollPane scrollPane1 = new JScrollPane();
        windowPanel.add(scrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        recentsPanel = new JPanel();
        recentsPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        scrollPane1.setViewportView(recentsPanel);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return windowPanel;
    }
}
