package com.defano.wyldcard.window.forms;

import com.defano.wyldcard.aspect.RunOnDispatch;
import com.defano.wyldcard.runtime.context.ToolsContext;
import com.defano.wyldcard.window.HyperCardDialog;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

public class IntensityPalette extends HyperCardDialog {
    private JSlider intensitySlider;
    private JPanel intensityPanel;

    public IntensityPalette() {
        intensitySlider.setValue((int) (ToolsContext.getInstance().getIntensity() * 100.0));
        intensitySlider.addChangeListener(e -> ToolsContext.getInstance().setIntensity(intensitySlider.getValue() / 100.0));
    }

    @Override
    public JComponent getWindowPanel() {
        return intensityPanel;
    }

    @Override
    @RunOnDispatch
    public void bindModel(Object data) {
        // Nothing to do
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        intensityPanel = new JPanel();
        intensityPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        intensitySlider = new JSlider();
        intensitySlider.setInverted(false);
        intensitySlider.setMajorTickSpacing(5);
        intensitySlider.setMaximum(30);
        intensitySlider.setMinimum(0);
        intensitySlider.setMinorTickSpacing(0);
        intensitySlider.setPaintLabels(false);
        intensitySlider.setPaintTicks(true);
        intensitySlider.setValueIsAdjusting(false);
        intensityPanel.add(intensitySlider, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        final Spacer spacer1 = new Spacer();
        intensityPanel.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return intensityPanel;
    }
}
