package hypercard.gui.window;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import hypercard.gui.HyperCardWindow;
import hypercard.gui.util.SquigglePainter;
import hypercard.parts.model.PartModel;
import hypercard.runtime.Interpreter;
import hypertalk.ast.common.Value;
import hypertalk.exception.HtException;
import hypertalk.exception.HtSyntaxException;

import javax.swing.*;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.BadLocationException;
import javax.swing.text.Highlighter;
import java.awt.*;

public class ScriptEditor implements HyperCardWindow {

    private final static Highlighter.HighlightPainter ERROR_HIGHLIGHTER = new SquigglePainter(Color.RED);

    private PartModel model;

    private JPanel scriptEditor;
    private JButton cancelButton;
    private JButton saveButton;
    private JTextArea scriptField;
    private JLabel errorText;

    public ScriptEditor() {

        cancelButton.addActionListener(e -> close());

        saveButton.addActionListener(e -> {
            updateProperties();
            close();
        });

        scriptField.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                checkSyntax();
            }

            public void removeUpdate(DocumentEvent e) {
                checkSyntax();
            }

            public void insertUpdate(DocumentEvent e) {
                checkSyntax();
            }
        });
    }

    private void checkSyntax() {
        try {
            Interpreter.compile(scriptField.getText());
            scriptField.getHighlighter().removeAllHighlights();
            errorText.setText("");
        } catch (HtSyntaxException e1) {
            errorText.setText(e1.getMessage());
            setHighlightedLine(e1.lineNumber - 1);
        } catch (HtException e1) {
            errorText.setText(e1.getMessage());
        }
    }

    private void setHighlightedLine(int line) {
        try {
            int lineStart = scriptField.getLineStartOffset(line);
            int lineEnd = scriptField.getLineEndOffset(line);

            scriptField.getHighlighter().addHighlight(lineStart, lineEnd, ERROR_HIGHLIGHTER);
        } catch (BadLocationException e) {
            // Nothing to do
        }
    }

    @Override
    public JPanel getWindowPanel() {
        return scriptEditor;
    }

    @Override
    public void bindModel(Object properties) {
        if (properties instanceof PartModel) {
            this.model = (PartModel) properties;
            scriptField.setText(this.model.getKnownProperty("script").stringValue());
        } else {
            throw new RuntimeException("Bug! Don't know how to bind data class to window." + properties);
        }
    }

    public void updateProperties() {
        model.setKnownProperty("script", new Value(scriptField.getText()));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        scriptEditor = new JPanel();
        scriptEditor.setLayout(new GridLayoutManager(2, 4, new Insets(10, 10, 10, 10), -1, -1));
        scriptEditor.setPreferredSize(new Dimension(640, 480));
        saveButton = new JButton();
        saveButton.setHideActionText(false);
        saveButton.setHorizontalAlignment(4);
        saveButton.setMargin(new Insets(0, 0, 0, 0));
        saveButton.setOpaque(true);
        saveButton.setText("Save");
        scriptEditor.add(saveButton, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        errorText = new JLabel();
        errorText.setText("");
        scriptEditor.add(errorText, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        scriptEditor.add(spacer1, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setFont(new Font("Monaco", scrollPane1.getFont().getStyle(), scrollPane1.getFont().getSize()));
        scriptEditor.add(scrollPane1, new GridConstraints(0, 0, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        scriptField = new JTextArea();
        scriptField.setFont(new Font("Monaco", scriptField.getFont().getStyle(), scriptField.getFont().getSize()));
        scriptField.setTabSize(4);
        scrollPane1.setViewportView(scriptField);
        cancelButton = new JButton();
        cancelButton.setHorizontalAlignment(4);
        cancelButton.setMargin(new Insets(0, 0, 0, 0));
        cancelButton.setText("Cancel");
        scriptEditor.add(cancelButton, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return scriptEditor;
    }
}
