package hypercard.gui.window;

import hypercard.context.ToolsContext;
import hypercard.gui.HyperCardWindow;
import hypercard.parts.CardPart;

import javax.swing.*;
import java.awt.*;

public class StackWindow extends HyperCardWindow {

    private CardPart card;
    private JPanel cardPanel;

    public CardPart getDisplayedCard() {
        return card;
    }

    public void setDisplayedCard(CardPart card) {
        this.card = card;

        cardPanel.removeAll();
        cardPanel.add(card);
        cardPanel.setPreferredSize(card.getSize());
        cardPanel.revalidate();
        cardPanel.repaint();

        ToolsContext.getInstance().reactivateTool(card.getCanvas());
    }

    @Override
    public JPanel getWindowPanel() {
        return cardPanel;
    }

    @Override
    public void bindModel(Object data) {
        if (data instanceof CardPart) {
            setDisplayedCard((CardPart) data);
        } else {
            throw new RuntimeException("Bug! Don't know how to bind data class to window." + data);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        cardPanel = new JPanel();
        cardPanel.setLayout(new BorderLayout(0, 0));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return cardPanel;
    }
}
