/** ButtonEditor.java
 * @author matt.defano@motorola.com
 * 
 * Implementation of the button properties editor. Generated using Netbeans IDE
 * Swing editor.
 */

package hypercard.gui;

import hypercard.parts.ButtonPart;
import hypertalk.ast.common.Value;
import hypertalk.properties.Properties;

import java.awt.Frame;
import java.io.Serializable;

/**
 *
 * @author  MGIA4532
 */
public class ButtonEditor extends javax.swing.JFrame implements Serializable {
private static final long serialVersionUID = 4162159591565669342L;

	private Properties properties;
    
    /** Creates new form FieldEditor */
    public ButtonEditor(Frame parent, Properties p) {
        this.properties = p;
        
        initComponents();
        loadValues();
        
        this.setLocationRelativeTo(parent);
    }
    
    private void loadValues() {
        jTextFieldButtonName.setText(properties.getKnownProperty(ButtonPart.PROP_NAME).stringValue());
        jTextFieldTitle.setText(properties.getKnownProperty(ButtonPart.PROP_TITLE).stringValue());
        
        jLabelTheId.setText(properties.getKnownProperty(ButtonPart.PROP_ID).stringValue());
        jTextFieldTop.setText(properties.getKnownProperty(ButtonPart.PROP_TOP).stringValue());
        jTextFieldLeft.setText(properties.getKnownProperty(ButtonPart.PROP_LEFT).stringValue());
        jTextFieldHeight.setText(properties.getKnownProperty(ButtonPart.PROP_HEIGHT).stringValue());
        jTextFieldWidth.setText(properties.getKnownProperty(ButtonPart.PROP_WIDTH).stringValue());
        jCheckBoxEnabled.setSelected(properties.getKnownProperty(ButtonPart.PROP_ENABLED).booleanValue());
        jCheckBoxShowTitle.setSelected(properties.getKnownProperty(ButtonPart.PROP_SHOWTITLE).booleanValue());
        jCheckBoxVisible.setSelected(properties.getKnownProperty(ButtonPart.PROP_VISIBLE).booleanValue());
    }
    
    private void saveValues() {
        try {
            properties.setProperty(ButtonPart.PROP_NAME, new Value(jTextFieldButtonName.getText()));
            properties.setProperty(ButtonPart.PROP_TITLE, new Value(jTextFieldTitle.getText()));
            
            properties.setProperty(ButtonPart.PROP_TOP, new Value(jTextFieldTop.getText()));
            properties.setProperty(ButtonPart.PROP_LEFT, new Value(jTextFieldLeft.getText()));
            properties.setProperty(ButtonPart.PROP_HEIGHT, new Value(jTextFieldHeight.getText()));
            properties.setProperty(ButtonPart.PROP_WIDTH, new Value(jTextFieldWidth.getText()));
            properties.setProperty(ButtonPart.PROP_ENABLED, new Value(jCheckBoxEnabled.getSelectedObjects() != null));
            properties.setProperty(ButtonPart.PROP_SHOWTITLE, new Value(jCheckBoxShowTitle.getSelectedObjects() != null));
            properties.setProperty(ButtonPart.PROP_VISIBLE, new Value(jCheckBoxVisible.getSelectedObjects() != null));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelIdentification = new javax.swing.JPanel();
        jLabelButtonName = new javax.swing.JLabel();
        jTextFieldButtonName = new javax.swing.JTextField();
        jLabelId = new javax.swing.JLabel();
        jLabelTheId = new javax.swing.JLabel();
        jPanelProperties = new javax.swing.JPanel();
        jLabelHeight = new javax.swing.JLabel();
        jTextFieldHeight = new javax.swing.JTextField();
        jLabelWidth = new javax.swing.JLabel();
        jTextFieldWidth = new javax.swing.JTextField();
        jCheckBoxVisible = new javax.swing.JCheckBox();
        jCheckBoxShowTitle = new javax.swing.JCheckBox();
        jLabelTop = new javax.swing.JLabel();
        jTextFieldLeft = new javax.swing.JTextField();
        jLabelLeft = new javax.swing.JLabel();
        jTextFieldTop = new javax.swing.JTextField();
        jLabelButtonTitle = new javax.swing.JLabel();
        jTextFieldTitle = new javax.swing.JTextField();
        jCheckBoxEnabled = new javax.swing.JCheckBox();
        jButtonEditScript = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setTitle("Button Properties Editor");

        jPanelIdentification.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Identification"));

        jLabelButtonName.setText("Button Name:");

        jLabelId.setText("ID:");

        jLabelTheId.setText("00000000");

        org.jdesktop.layout.GroupLayout jPanelIdentificationLayout = new org.jdesktop.layout.GroupLayout(jPanelIdentification);
        jPanelIdentification.setLayout(jPanelIdentificationLayout);
        jPanelIdentificationLayout.setHorizontalGroup(
            jPanelIdentificationLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelIdentificationLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelIdentificationLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabelButtonName)
                    .add(jLabelId))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelIdentificationLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextFieldButtonName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                    .add(jLabelTheId))
                .addContainerGap())
        );
        jPanelIdentificationLayout.setVerticalGroup(
            jPanelIdentificationLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelIdentificationLayout.createSequentialGroup()
                .add(jPanelIdentificationLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelButtonName)
                    .add(jTextFieldButtonName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelIdentificationLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelId)
                    .add(jLabelTheId))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelProperties.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Properties"));

        jLabelHeight.setText("Height:");

        jLabelWidth.setText("Width:");

        jCheckBoxVisible.setSelected(true);
        jCheckBoxVisible.setText("Visible");
        jCheckBoxVisible.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBoxVisible.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jCheckBoxShowTitle.setSelected(true);
        jCheckBoxShowTitle.setText("Show Title");
        jCheckBoxShowTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBoxShowTitle.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabelTop.setText("Top:");

        jLabelLeft.setText("Left:");

        jLabelButtonTitle.setText("Button Title:");

        jTextFieldTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTitleActionPerformed(evt);
            }
        });

        jCheckBoxEnabled.setSelected(true);
        jCheckBoxEnabled.setText("Enabled");

        org.jdesktop.layout.GroupLayout jPanelPropertiesLayout = new org.jdesktop.layout.GroupLayout(jPanelProperties);
        jPanelProperties.setLayout(jPanelPropertiesLayout);
        jPanelPropertiesLayout.setHorizontalGroup(
            jPanelPropertiesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelPropertiesLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelPropertiesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelPropertiesLayout.createSequentialGroup()
                        .add(jPanelPropertiesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabelHeight)
                            .add(jLabelWidth))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanelPropertiesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jTextFieldWidth)
                            .add(jTextFieldHeight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanelPropertiesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanelPropertiesLayout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jLabelTop)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jTextFieldTop, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                            .add(jPanelPropertiesLayout.createSequentialGroup()
                                .add(jLabelLeft)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jTextFieldLeft, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)))
                        .add(50, 50, 50)
                        .add(jPanelPropertiesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jCheckBoxShowTitle)
                            .add(jPanelPropertiesLayout.createSequentialGroup()
                                .add(jCheckBoxVisible)
                                .add(12, 12, 12)
                                .add(jCheckBoxEnabled))))
                    .add(jPanelPropertiesLayout.createSequentialGroup()
                        .add(jLabelButtonTitle)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextFieldTitle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelPropertiesLayout.setVerticalGroup(
            jPanelPropertiesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelPropertiesLayout.createSequentialGroup()
                .add(jPanelPropertiesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelButtonTitle)
                    .add(jTextFieldTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 17, Short.MAX_VALUE)
                .add(jPanelPropertiesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelHeight)
                    .add(jTextFieldHeight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jCheckBoxVisible)
                    .add(jTextFieldTop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelTop)
                    .add(jCheckBoxEnabled))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelPropertiesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelWidth)
                    .add(jTextFieldWidth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jCheckBoxShowTitle)
                    .add(jLabelLeft)
                    .add(jTextFieldLeft, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButtonEditScript.setText("Edit Script...");
        jButtonEditScript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditScriptActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanelProperties, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanelIdentification, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(jButtonEditScript)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 159, Short.MAX_VALUE)
                        .add(jButtonCancel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButtonSave)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelIdentification, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelProperties, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonEditScript)
                    .add(jButtonSave)
                    .add(jButtonCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditScriptActionPerformed
        String theScript = properties.getKnownProperty(ButtonPart.PROP_SCRIPT).stringValue();
        ScriptEditor se = new ScriptEditor(this, theScript);
        se.setVisible(true);
        
        try {
            if (!se.wasCanceled())
                properties.setProperty(ButtonPart.PROP_SCRIPT, new Value(se.getScript()));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }//GEN-LAST:event_jButtonEditScriptActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        saveValues();
        this.dispose();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jTextFieldTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTitleActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldTitleActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonEditScript;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JCheckBox jCheckBoxEnabled;
    private javax.swing.JCheckBox jCheckBoxShowTitle;
    private javax.swing.JCheckBox jCheckBoxVisible;
    private javax.swing.JLabel jLabelButtonName;
    private javax.swing.JLabel jLabelButtonTitle;
    private javax.swing.JLabel jLabelHeight;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelLeft;
    private javax.swing.JLabel jLabelTheId;
    private javax.swing.JLabel jLabelTop;
    private javax.swing.JLabel jLabelWidth;
    private javax.swing.JPanel jPanelIdentification;
    private javax.swing.JPanel jPanelProperties;
    private javax.swing.JTextField jTextFieldButtonName;
    private javax.swing.JTextField jTextFieldHeight;
    private javax.swing.JTextField jTextFieldLeft;
    private javax.swing.JTextField jTextFieldTitle;
    private javax.swing.JTextField jTextFieldTop;
    private javax.swing.JTextField jTextFieldWidth;
    // End of variables declaration//GEN-END:variables
    
}
