package com.defano.hypertalk;

import com.defano.hypercard.runtime.context.HyperCardProperties;
import com.defano.hypercard.parts.card.CardLayerPartModel;
import com.defano.hypercard.parts.model.PartModel;
import com.defano.hypertalk.ast.common.*;
import com.defano.hypertalk.ast.constructs.*;
import com.defano.hypertalk.ast.containers.*;
import com.defano.hypertalk.ast.expressions.*;
import com.defano.hypertalk.ast.functions.*;
import com.defano.hypertalk.ast.specifiers.*;
import com.defano.hypertalk.ast.statements.*;
import com.defano.hypertalk.ast.commands.*;
import com.defano.hypertalk.comparator.SortStyle;
import com.defano.hypertalk.parser.HyperTalkBaseVisitor;
import com.defano.hypertalk.parser.HyperTalkParser;
import com.defano.jsegue.SegueName;
import org.antlr.v4.runtime.tree.TerminalNode;

/**
 * Converts an Antlr parse tree into a HyperTalk abstract syntax tree using Antlr's visitor pattern. The HyperTalk
 * grammar is defined in HyperTalk.g4.
 *
 * In Antlr4, parse trees generated by the parser are effectively immutable. This class walks that immutable parse tree
 * ("visits" each node in it) and generates an alternate representation of the language consisting of {@link Expression}
 * and {@link Statement} nodes that bind some behavior or action to each node in the syntax tree.
 *
 * There is approximately (but not exactly) a one-to-one relationship between nodes in the parse tree and in the AST.
 * In some cases, it was more effective to introduce grammar constructs useful for parsing, but which do not represent
 * either a valid expression or statement (like date/time conversion formats); these represent nodes in the parse tree
 * which are "gobbled up" by this visitor and do not yield a corresponding node in the AST.
 *
 * Each method in this class corresponds to a "label" in the grammar (i.e., the symbol to the right of the '#'). As you
 * add production rules to the grammar you must implement the corresponding visitor method to produce an AST node.
 */
public class HyperTalkTreeVisitor extends HyperTalkBaseVisitor<Object> {

    @Override
    public Object visitHandlerScript(HyperTalkParser.HandlerScriptContext ctx) {
        Script script = (Script) visit(ctx.script());
        script.defineHandler((NamedBlock) visit(ctx.handler()), ctx.handler().getStart().getLine(), ctx.handler().getStop().getLine());
        return script;
    }

    @Override
    public Object visitFunctionScript(HyperTalkParser.FunctionScriptContext ctx) {
        Script script = (Script) visit(ctx.script());
        script.defineUserFunction((UserFunction) visit(ctx.function()), ctx.function().getStart().getLine(), ctx.function().getStop().getLine());
        return script;
    }

    @Override
    public Object visitNewlineScript(HyperTalkParser.NewlineScriptContext ctx) {
        return visit(ctx.script());
    }

    @Override
    public Object visitHideCmdStmnt(HyperTalkParser.HideCmdStmntContext ctx) {
        return new SetPropertyCmd(ctx, (PartExp) visit(ctx.part()), PartModel.PROP_VISIBLE, new Value(false));
    }

    @Override
    public Object visitShowCmdStmnt(HyperTalkParser.ShowCmdStmntContext ctx) {
        return new SetPropertyCmd(ctx, (PartExp) visit(ctx.part()), PartModel.PROP_VISIBLE, new Value(true));
    }

    @Override
    public Object visitWaitCountCmd(HyperTalkParser.WaitCountCmdContext ctx) {
        return new WaitCmd(ctx, (Expression) visit(ctx.factor()), (TimeUnit) visit(ctx.timeUnit()));
    }

    @Override
    public Object visitWaitUntilCmd(HyperTalkParser.WaitUntilCmdContext ctx) {
        return new WaitCmd(ctx, (Expression) visit(ctx.expression()), true);
    }

    @Override
    public Object visitWaitWhileCmd(HyperTalkParser.WaitWhileCmdContext ctx) {
        return new WaitCmd(ctx, (Expression) visit(ctx.expression()), false);
    }

    @Override
    public Object visitSortDirectionCmd(HyperTalkParser.SortDirectionCmdContext ctx) {
        return new SortCmd(ctx, (Container) visit(ctx.container()), (ChunkType) visit(ctx.sortChunkType()), (SortDirection) visit(ctx.sortDirection()), (SortStyle) visit(ctx.sortStyle()));
    }

    @Override
    public Object visitSortExpressionCmd(HyperTalkParser.SortExpressionCmdContext ctx) {
        return new SortCmd(ctx, (Container) visit(ctx.container()), (ChunkType) visit(ctx.sortChunkType()), (Expression) visit(ctx.expression()), (SortDirection) visit(ctx.sortDirection()), (SortStyle) visit(ctx.sortStyle()));
    }

    @Override
    public Object visitSortMarkedCardsCmd(HyperTalkParser.SortMarkedCardsCmdContext ctx) {
        return new SortCardsCmd(ctx, true, (SortDirection) visit(ctx.sortDirection()), (SortStyle) visit(ctx.sortStyle()), (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitSortStackCmd(HyperTalkParser.SortStackCmdContext ctx) {
        return new SortCardsCmd(ctx, false, (SortDirection) visit(ctx.sortDirection()), (SortStyle) visit(ctx.sortStyle()), (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitSortBkgndCardsCmd(HyperTalkParser.SortBkgndCardsCmdContext ctx) {
        return new SortCardsCmd(ctx, false, (PartExp) visit(ctx.bkgndPart()), (SortDirection) visit(ctx.sortDirection()), (SortStyle) visit(ctx.sortStyle()), (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitSortMarkedBkgndCardsCmd(HyperTalkParser.SortMarkedBkgndCardsCmdContext ctx) {
        return new SortCardsCmd(ctx, true, (PartExp) visit(ctx.bkgndPart()), (SortDirection) visit(ctx.sortDirection()), (SortStyle) visit(ctx.sortStyle()), (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitKeywordToolExpr(HyperTalkParser.KeywordToolExprContext ctx) {
        return new LiteralExp(ctx, ctx.getText());
    }

    @Override
    public Object visitToolExpr(HyperTalkParser.ToolExprContext ctx) {
        return visit(ctx.expression());
    }

    @Override
    public Object visitConvertContainerFromToCmd(HyperTalkParser.ConvertContainerFromToCmdContext ctx) {
        return new ConvertCmd(ctx, (Container) visit(ctx.container()), (Convertible) visit(ctx.convertible(0)), (Convertible) visit(ctx.convertible(1)));
    }

    @Override
    public Object visitConvertContainerToCmd(HyperTalkParser.ConvertContainerToCmdContext ctx) {
        return new ConvertCmd(ctx, (Container) visit(ctx.container()), (Convertible) visit(ctx.convertible()));
    }

    @Override
    public Object visitConvertToCmd(HyperTalkParser.ConvertToCmdContext ctx) {
        return new ConvertCmd(ctx, (Expression) visit(ctx.expression()), (Convertible) visit(ctx.convertible()));
    }

    @Override
    public Object visitConvertFromToCmd(HyperTalkParser.ConvertFromToCmdContext ctx) {
        return new ConvertCmd(ctx, (Expression) visit(ctx.expression()), (Convertible) visit(ctx.convertible(0)), (Convertible) visit(ctx.convertible(1)));
    }

    @Override
    public Object visitDualFormatConvertible(HyperTalkParser.DualFormatConvertibleContext ctx) {
        return new Convertible((ConvertibleDateFormat) visit(ctx.conversionFormat(0)), (ConvertibleDateFormat) visit(ctx.conversionFormat(1)));
    }

    @Override
    public Object visitSingleFormatConvertible(HyperTalkParser.SingleFormatConvertibleContext ctx) {
        return new Convertible((ConvertibleDateFormat) visit(ctx.conversionFormat()));
    }

    @Override
    public Object visitDateItemsConvFormat(HyperTalkParser.DateItemsConvFormatContext ctx) {
        return ConvertibleDateFormat.DATE_ITEMS;
    }

    @Override
    public Object visitDateConvFormat(HyperTalkParser.DateConvFormatContext ctx) {
        return ConvertibleDateFormat.ofDateLength((DateLength) visit(ctx.timeDateFormat()));
    }

    @Override
    public Object visitTimeConvFormat(HyperTalkParser.TimeConvFormatContext ctx) {
        return ConvertibleDateFormat.ofTimeLength((DateLength) visit(ctx.timeDateFormat()));
    }

    @Override
    public Object visitSecondsConvFormat(HyperTalkParser.SecondsConvFormatContext ctx) {
        return ConvertibleDateFormat.SECONDS;
    }

    @Override
    public Object visitSortDirectionAsc(HyperTalkParser.SortDirectionAscContext ctx) {
        return SortDirection.ASCENDING;
    }

    @Override
    public Object visitSortDirectionDesc(HyperTalkParser.SortDirectionDescContext ctx) {
        return SortDirection.DESCENDING;
    }

    @Override
    public Object visitSortDirectionDefault(HyperTalkParser.SortDirectionDefaultContext ctx) {
        return SortDirection.ASCENDING;
    }

    @Override
    public Object visitSortChunkLines(HyperTalkParser.SortChunkLinesContext ctx) {
        return ChunkType.LINE;
    }

    @Override
    public Object visitSortChunkItems(HyperTalkParser.SortChunkItemsContext ctx) {
        return ChunkType.ITEM;
    }

    @Override
    public Object visitSortChunkDefault(HyperTalkParser.SortChunkDefaultContext ctx) {
        return ChunkType.LINE;
    }

    @Override
    public Object visitSortStyleText(HyperTalkParser.SortStyleTextContext ctx) {
        return SortStyle.TEXT;
    }

    @Override
    public Object visitSortStyleNumeric(HyperTalkParser.SortStyleNumericContext ctx) {
        return SortStyle.NUMERIC;
    }

    @Override
    public Object visitSortStyleInternational(HyperTalkParser.SortStyleInternationalContext ctx) {
        return SortStyle.INTERNATIONAL;
    }

    @Override
    public Object visitSortStyleDateTime(HyperTalkParser.SortStyleDateTimeContext ctx) {
        return SortStyle.DATE_TIME;
    }

    @Override
    public Object visitSortStyleDefault(HyperTalkParser.SortStyleDefaultContext ctx) {
        return SortStyle.TEXT;
    }

    @Override
    public Object visitEffectDefault(HyperTalkParser.EffectDefaultContext ctx) {
        return new VisualEffectSpecifier((SegueName) visit(ctx.effect()));
    }

    @Override
    public Object visitEffectTo(HyperTalkParser.EffectToContext ctx) {
        return new VisualEffectSpecifier((SegueName) visit(ctx.effect()), (VisualEffectImage) visit(ctx.image()));
    }

    @Override
    public Object visitEffectSpeed(HyperTalkParser.EffectSpeedContext ctx) {
        return new VisualEffectSpecifier((SegueName) visit(ctx.effect()), (VisualEffectSpeed) visit(ctx.speed()));
    }

    @Override
    public Object visitEffectSpeedTo(HyperTalkParser.EffectSpeedToContext ctx) {
        return new VisualEffectSpecifier((SegueName) visit(ctx.effect()), (VisualEffectSpeed) visit(ctx.speed()), (VisualEffectImage) visit(ctx.image()));
    }

    @Override
    public Object visitFastSpeed(HyperTalkParser.FastSpeedContext ctx) {
        return VisualEffectSpeed.FAST;
    }

    @Override
    public Object visitSlowSpeed(HyperTalkParser.SlowSpeedContext ctx) {
        return VisualEffectSpeed.SLOW;
    }

    @Override
    public Object visitVeryFastSpeed(HyperTalkParser.VeryFastSpeedContext ctx) {
        return VisualEffectSpeed.VERY_FAST;
    }

    @Override
    public Object visitVerySlowSpeed(HyperTalkParser.VerySlowSpeedContext ctx) {
        return VisualEffectSpeed.SLOW;
    }

    @Override
    public Object visitBlackImage(HyperTalkParser.BlackImageContext ctx) {
        return VisualEffectImage.BLACK;
    }

    @Override
    public Object visitCardImage(HyperTalkParser.CardImageContext ctx) {
        return VisualEffectImage.CARD;
    }

    @Override
    public Object visitGrayImage(HyperTalkParser.GrayImageContext ctx) {
        return VisualEffectImage.GRAY;
    }

    @Override
    public Object visitInverseImage(HyperTalkParser.InverseImageContext ctx) {
        return VisualEffectImage.INVERSE;
    }

    @Override
    public Object visitWhiteImage(HyperTalkParser.WhiteImageContext ctx) {
        return VisualEffectImage.WHITE;
    }

    @Override
    public Object visitDissolveEffect(HyperTalkParser.DissolveEffectContext ctx) {
        return SegueName.DISSOLVE;
    }

    @Override
    public Object visitBarnDoorOpenEffect(HyperTalkParser.BarnDoorOpenEffectContext ctx) {
        return SegueName.BARN_DOOR_OPEN;
    }

    @Override
    public Object visitBarnDoorCloseEffect(HyperTalkParser.BarnDoorCloseEffectContext ctx) {
        return SegueName.BARN_DOOR_CLOSE;
    }

    @Override
    public Object visitCheckerboardEffect(HyperTalkParser.CheckerboardEffectContext ctx) {
        return SegueName.CHECKERBOARD;
    }

    @Override
    public Object visitIrisOpenEffect(HyperTalkParser.IrisOpenEffectContext ctx) {
        return SegueName.IRIS_OPEN;
    }

    @Override
    public Object visitIrisCloseEffect(HyperTalkParser.IrisCloseEffectContext ctx) {
        return SegueName.IRIS_CLOSE;
    }

    @Override
    public Object visitPlainEffect(HyperTalkParser.PlainEffectContext ctx) {
        return SegueName.PLAIN;
    }

    @Override
    public Object visitPushUpEffect(HyperTalkParser.PushUpEffectContext ctx) {
        return SegueName.SCROLL_UP;
    }

    @Override
    public Object visitPushDownEffect(HyperTalkParser.PushDownEffectContext ctx) {
        return SegueName.SCROLL_DOWN;
    }

    @Override
    public Object visitPushLeftEffect(HyperTalkParser.PushLeftEffectContext ctx) {
        return SegueName.SCROLL_LEFT;
    }

    @Override
    public Object visitPushRightEffect(HyperTalkParser.PushRightEffectContext ctx) {
        return SegueName.SCROLL_RIGHT;
    }

    @Override
    public Object visitScrollDownEffect(HyperTalkParser.ScrollDownEffectContext ctx) {
        return SegueName.SCROLL_DOWN;
    }

    @Override
    public Object visitScrollUpEffect(HyperTalkParser.ScrollUpEffectContext ctx) {
        return SegueName.SCROLL_UP;
    }

    @Override
    public Object visitScrollLeftEffect(HyperTalkParser.ScrollLeftEffectContext ctx) {
        return SegueName.SCROLL_LEFT;
    }

    @Override
    public Object visitScrollRightEffect(HyperTalkParser.ScrollRightEffectContext ctx) {
        return SegueName.SCROLL_RIGHT;
    }

    @Override
    public Object visitShrinkToTopEffect(HyperTalkParser.ShrinkToTopEffectContext ctx) {
        return SegueName.SHRINK_TO_TOP;
    }

    @Override
    public Object visitShrinkToCenterEffect(HyperTalkParser.ShrinkToCenterEffectContext ctx) {
        return SegueName.SHRINK_TO_CENTER;
    }

    @Override
    public Object visitShrinkToBottomEffect(HyperTalkParser.ShrinkToBottomEffectContext ctx) {
        return SegueName.SHRINK_TO_BOTTOM;
    }

    @Override
    public Object visitStretchFromTopEffect(HyperTalkParser.StretchFromTopEffectContext ctx) {
        return SegueName.STRETCH_FROM_TOP;
    }

    @Override
    public Object visitStretchFromCenterEffect(HyperTalkParser.StretchFromCenterEffectContext ctx) {
        return SegueName.STRETCH_FROM_CENTER;
    }

    @Override
    public Object visitStretchFromBottomEffect(HyperTalkParser.StretchFromBottomEffectContext ctx) {
        return SegueName.STRETCH_FROM_BOTTOM;
    }

    @Override
    public Object visitVenitianBlindsEffect(HyperTalkParser.VenitianBlindsEffectContext ctx) {
        return SegueName.VENETIAN_BLINDS;
    }

    @Override
    public Object visitZoomInEffect(HyperTalkParser.ZoomInEffectContext ctx) {
        return SegueName.ZOOM_IN;
    }

    @Override
    public Object visitZoomOutEffect(HyperTalkParser.ZoomOutEffectContext ctx) {
        return SegueName.ZOOM_OUT;
    }

    @Override
    public Object visitZoomOpenEffect(HyperTalkParser.ZoomOpenEffectContext ctx) {
        return SegueName.ZOOM_OUT;
    }

    @Override
    public Object visitZoomCloseEffect(HyperTalkParser.ZoomCloseEffectContext ctx) {
        return SegueName.ZOOM_IN;
    }

    @Override
    public Object visitWipeUpEffect(HyperTalkParser.WipeUpEffectContext ctx) {
        return SegueName.WIPE_UP;
    }

    @Override
    public Object visitWipeDownEffect(HyperTalkParser.WipeDownEffectContext ctx) {
        return SegueName.WIPE_DOWN;
    }

    @Override
    public Object visitWipeLeftEffect(HyperTalkParser.WipeLeftEffectContext ctx) {
        return SegueName.WIPE_LEFT;
    }

    @Override
    public Object visitWipeRightEffect(HyperTalkParser.WipeRightEffectContext ctx) {
        return SegueName.WIPE_RIGHT;
    }

    @Override
    public Object visitTicksTimeUnit(HyperTalkParser.TicksTimeUnitContext ctx) {
        return TimeUnit.TICKS;
    }

    @Override
    public Object visitSecondsTimeUnit(HyperTalkParser.SecondsTimeUnitContext ctx) {
        return TimeUnit.SECONDS;
    }

    @Override
    public Object visitGoCmdStmnt(HyperTalkParser.GoCmdStmntContext ctx) {
        return new GoCmd(ctx, (DestinationExp) visit(ctx.destination()));
    }

    @Override
    public Object visitGoBackCmdStmt(HyperTalkParser.GoBackCmdStmtContext ctx) {
        return new GoCmd(ctx, null);
    }

    @Override
    public Object visitGoBackVisualEffectCmdStmt(HyperTalkParser.GoBackVisualEffectCmdStmtContext ctx) {
        return new GoCmd(ctx, null, (VisualEffectSpecifier) visit(ctx.visualEffect()));
    }

    @Override
    public Object visitGoVisualEffectCmdStmnd(HyperTalkParser.GoVisualEffectCmdStmndContext ctx) {
        return new GoCmd(ctx, (DestinationExp) visit(ctx.destination()), (VisualEffectSpecifier) visit(ctx.visualEffect()));
    }

    @Override
    public Object visitNextPosition(HyperTalkParser.NextPositionContext ctx) {
        return Position.NEXT;
    }

    @Override
    public Object visitPrevPosition(HyperTalkParser.PrevPositionContext ctx) {
        return Position.PREV;
    }

    @Override
    public Object visitThisPosition(HyperTalkParser.ThisPositionContext ctx) {
        return Position.THIS;
    }

    @Override
    public Object visitCardNumber(HyperTalkParser.CardNumberContext ctx) {
        return new DestinationNumberExp(ctx, (Expression) visit(ctx.expression()), (DestinationType) visit(ctx.destinationType()));
    }

    @Override
    public Object visitCardOrdinal(HyperTalkParser.CardOrdinalContext ctx) {
        return new DestinationOrdinalExp(ctx, (Ordinal) visit(ctx.ordinal()), (DestinationType) visit(ctx.destinationType()));
    }

    @Override
    public Object visitCardPosition(HyperTalkParser.CardPositionContext ctx) {
        return new DestinationPositionExp(ctx, (Position) visit(ctx.position()), (DestinationType) visit(ctx.destinationType()));
    }

    @Override
    public Object visitDestinationRef(HyperTalkParser.DestinationRefContext ctx) {
        return new DestinationReferenceExp(ctx, (Expression) visit(ctx.factor()));
    }

    @Override
    public Object visitCardDestinationType(HyperTalkParser.CardDestinationTypeContext ctx) {
        return DestinationType.CARD;
    }

    @Override
    public Object visitBkgndDestinationType(HyperTalkParser.BkgndDestinationTypeContext ctx) {
        return DestinationType.BACKGROUND;
    }

    @Override
    public Object visitPropertyDest(HyperTalkParser.PropertyDestContext ctx) {
        return new PropertyContainer((PropertySpecifier) visit(ctx.property()));
    }

    @Override
    public Object visitMenuDest(HyperTalkParser.MenuDestContext ctx) {
        return new MenuContainer((MenuSpecifier) visit(ctx.menu()));
    }

    @Override
    public Object visitMenuItemDest(HyperTalkParser.MenuItemDestContext ctx) {
        return new MenuContainer((MenuItemSpecifier) visit(ctx.menuItem()));
    }

    @Override
    public Object visitMessageDest(HyperTalkParser.MessageDestContext ctx) {
        return new MsgBoxContainer();
    }

    @Override
    public Object visitChunkContainerDest(HyperTalkParser.ChunkContainerDestContext ctx) {
        Container container = (Container) visit(ctx.container());
        container.setChunk((Chunk) visit(ctx.chunk()));
        return container;
    }

    @Override
    public Object visitEmptyScript(HyperTalkParser.EmptyScriptContext ctx) {
        return new Script();
    }

    @Override
    public Object visitStatementScriptlet(HyperTalkParser.StatementScriptletContext ctx) {
        Script script = (Script) visit(ctx.scriptlet());
        return script.insertStatement((Statement) visit(ctx.statement()));
    }

    @Override
    public Object visitSingleStatementScriptlet(HyperTalkParser.SingleStatementScriptletContext ctx) {
        Script script = new Script();
        return script.insertStatement((Statement) visit(ctx.statement()));
    }

    @Override
    public Object visitEmptyScriptlet(HyperTalkParser.EmptyScriptletContext ctx) {
        return new Script();
    }

    @Override
    public Object visitNoArgHandler(HyperTalkParser.NoArgHandlerContext ctx) {
        StatementList statements = ctx.statementList() == null ? new StatementList(ctx) : (StatementList) visit(ctx.statementList());
        return new NamedBlock((String) visit(ctx.handlerName(0)), (String) visit(ctx.handlerName(1)), statements);
    }

    @Override
    public Object visitArgHandler(HyperTalkParser.ArgHandlerContext ctx) {
        StatementList statements = ctx.statementList() == null ? new StatementList(ctx) : (StatementList) visit(ctx.statementList());
        return new NamedBlock((String) visit(ctx.handlerName(0)), (String) visit(ctx.handlerName(1)), (ParameterList) visit(ctx.parameterList()), statements);
    }

    @Override
    public Object visitNoArgFunction(HyperTalkParser.NoArgFunctionContext ctx) {
        StatementList statements = ctx.statementList() == null ? new StatementList(ctx) : (StatementList) visit(ctx.statementList());
        return new UserFunction((String) visit(ctx.ID(0)), (String) visit(ctx.ID(1)), new ParameterList(), statements);
    }

    @Override
    public Object visitArgFunction(HyperTalkParser.ArgFunctionContext ctx) {
        StatementList statements = ctx.statementList() == null ? new StatementList(ctx) : (StatementList) visit(ctx.statementList());
        return new UserFunction((String) visit(ctx.ID(0)), (String) visit(ctx.ID(1)), (ParameterList) visit(ctx.parameterList()), statements);
    }

    @Override
    public Object visitHandlerName(HyperTalkParser.HandlerNameContext ctx) {
        return super.visitHandlerName(ctx);
    }

    @Override
    public Object visitSingleExpArgList(HyperTalkParser.SingleExpArgListContext ctx) {
        return new ExpressionList((Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitMultiExpArgList(HyperTalkParser.MultiExpArgListContext ctx) {
        ExpressionList argumentList = (ExpressionList) visit(ctx.argumentList());
        argumentList.addArgument((Expression) visit(ctx.expression()));
        return argumentList;
    }

    @Override
    public Object visitSingleParamList(HyperTalkParser.SingleParamListContext ctx) {
        return new ParameterList((String) visit(ctx.ID()));
    }

    @Override
    public Object visitMultiParamList(HyperTalkParser.MultiParamListContext ctx) {
        ParameterList parameterList = (ParameterList) visit(ctx.parameterList());
        parameterList.addParameter((String) visit(ctx.ID()));
        return parameterList;
    }

    @Override
    public Object visitSingleStmntList(HyperTalkParser.SingleStmntListContext ctx) {
        return new StatementList(ctx, (Statement) visit(ctx.statement()));
    }

    @Override
    public Object visitMultiStmntList(HyperTalkParser.MultiStmntListContext ctx) {
        StatementList statementList = (StatementList) visit(ctx.statementList());
        statementList.append((Statement) visit(ctx.statement()));
        return statementList;
    }

    @Override
    public Object visitNonEmptyCommandStmnt(HyperTalkParser.NonEmptyCommandStmntContext ctx) {
        return visit(ctx.commandStmnt());
    }

    @Override
    public Object visitNonEmptyFuncStmnt(HyperTalkParser.NonEmptyFuncStmntContext ctx) {
        return new ExpressionStatement(ctx, (Expression) visit(ctx.functionCall()));
    }

    @Override
    public Object visitNonEmptyGlobalStmnt(HyperTalkParser.NonEmptyGlobalStmntContext ctx) {
        return visit(ctx.globalStmnt());
    }

    @Override
    public Object visitNonEmptyIfStmnt(HyperTalkParser.NonEmptyIfStmntContext ctx) {
        return visit(ctx.ifStatement());
    }

    @Override
    public Object visitNonEmptyRepeatStmnt(HyperTalkParser.NonEmptyRepeatStmntContext ctx) {
        return visit(ctx.repeatStatement());
    }

    @Override
    public Object visitNonEmptyReturnStmnt(HyperTalkParser.NonEmptyReturnStmntContext ctx) {
        return visit(ctx.returnStmnt());
    }

    @Override
    public Object visitNonEmptyExpStmnt(HyperTalkParser.NonEmptyExpStmntContext ctx) {
        return new ExpressionStatement(ctx, (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitNonEmptyMsgStmnt(HyperTalkParser.NonEmptyMsgStmntContext ctx) {
        return super.visitNonEmptyMsgStmnt(ctx);
    }

    @Override
    public Object visitVoidReturnStmnt(HyperTalkParser.VoidReturnStmntContext ctx) {
        return new ReturnStatement(ctx);
    }

    @Override
    public Object visitEprReturnStmnt(HyperTalkParser.EprReturnStmntContext ctx) {
        return new ReturnStatement(ctx, (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitGetCmdStmnt(HyperTalkParser.GetCmdStmntContext ctx) {
        return new GetCmd(ctx, (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitSetCmdStmnt(HyperTalkParser.SetCmdStmntContext ctx) {
        return new SetCmd(ctx, (PropertySpecifier) visit(ctx.property()), (Expression) visit(ctx.propertyValue()));
    }

    @Override
    public Object visitSendCmdStmnt(HyperTalkParser.SendCmdStmntContext ctx) {
        return new SendCmd(ctx, (PartExp) visit(ctx.part()), (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitAddCmdStmnt(HyperTalkParser.AddCmdStmntContext ctx) {
        return new AddCmd(ctx, (Expression) visit(ctx.expression()), (Container) visit(ctx.container()));
    }

    @Override
    public Object visitSubtractCmdStmnt(HyperTalkParser.SubtractCmdStmntContext ctx) {
        return new SubtractCmd(ctx, (Expression) visit(ctx.expression()), (Container) visit(ctx.container()));
    }

    @Override
    public Object visitMultiplyCmdStmnt(HyperTalkParser.MultiplyCmdStmntContext ctx) {
        return new MultiplyCmd(ctx, (Expression) visit(ctx.expression()), (Container) visit(ctx.container()));
    }

    @Override
    public Object visitDivideCmdStmnt(HyperTalkParser.DivideCmdStmntContext ctx) {
        return new DivideCmd(ctx, (Expression) visit(ctx.expression()), (Container) visit(ctx.container()));
    }

    @Override
    public Object visitDoCmdStmt(HyperTalkParser.DoCmdStmtContext ctx) {
        return new DoCmd(ctx, (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitChooseToolCmdStmt(HyperTalkParser.ChooseToolCmdStmtContext ctx) {
        return new ChooseCmd(ctx, (Expression) visit(ctx.toolExpression()));
    }

    @Override
    public Object visitChooseToolNumberCmdStmt(HyperTalkParser.ChooseToolNumberCmdStmtContext ctx) {
        return new ChooseCmd(ctx, (Expression) visit(ctx.toolExpression()));
    }

    @Override
    public Object visitClickCmdStmt(HyperTalkParser.ClickCmdStmtContext ctx) {
        return new ClickCmd(ctx, (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitClickWithKeyCmdStmt(HyperTalkParser.ClickWithKeyCmdStmtContext ctx) {
        return new ClickCmd(ctx, (Expression) visit(ctx.expression()), (ExpressionList) visit(ctx.argumentList()));
    }

    @Override
    public Object visitDragCmdStmt(HyperTalkParser.DragCmdStmtContext ctx) {
        return new DragCmd(ctx, (Expression) visit(ctx.expression(0)), (Expression) visit(ctx.expression(1)));
    }

    @Override
    public Object visitDragWithKeyCmdStmt(HyperTalkParser.DragWithKeyCmdStmtContext ctx) {
        return new DragCmd(ctx, (Expression) visit(ctx.expression(0)), (Expression) visit(ctx.expression(1)), (ExpressionList) visit(ctx.argumentList()));
    }

    @Override
    public Object visitTypeCmdStmt(HyperTalkParser.TypeCmdStmtContext ctx) {
        return new TypeCmd(ctx, (Expression) visit(ctx.expression()), false);
    }

    @Override
    public Object visitTypeWithCmdKeyCmdStmt(HyperTalkParser.TypeWithCmdKeyCmdStmtContext ctx) {
        return new TypeCmd(ctx, (Expression) visit(ctx.expression()), true);
    }

    @Override
    public Object visitDeleteCmdStmt(HyperTalkParser.DeleteCmdStmtContext ctx) {
        return new DeletePartCmd(ctx, (PartExp) visit(ctx.part()));
    }

    @Override
    public Object visitDeleteChunkCmdStmt(HyperTalkParser.DeleteChunkCmdStmtContext ctx) {
        return new DeleteChunkCmd(ctx, (Container) visit(ctx.container()));
    }

    @Override
    public Object visitPlayCmdStmt(HyperTalkParser.PlayCmdStmtContext ctx) {
        return new PlayCmd(ctx, (MusicSpecifier) visit(ctx.musicExpression()));
    }

    @Override
    public Object visitDialCmdStmt(HyperTalkParser.DialCmdStmtContext ctx) {
        return new DialCmd(ctx, (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitBeepCmdStmt(HyperTalkParser.BeepCmdStmtContext ctx) {
        return new BeepCmd(ctx);
    }

    @Override
    public Object visitBeepMultipleStmt(HyperTalkParser.BeepMultipleStmtContext ctx) {
        return new BeepCmd(ctx, (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitOpenFileCmdStmt(HyperTalkParser.OpenFileCmdStmtContext ctx) {
        return new OpenCmd(ctx, (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitCloseFileCmdStmt(HyperTalkParser.CloseFileCmdStmtContext ctx) {
        return new CloseCmd(ctx, (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitNextRepeatCmdStmt(HyperTalkParser.NextRepeatCmdStmtContext ctx) {
        return new NextRepeatStatement(ctx);
    }

    @Override
    public Object visitExitRepeatCmdStmt(HyperTalkParser.ExitRepeatCmdStmtContext ctx) {
        return new ExitRepeatStatement(ctx);
    }

    @Override
    public Object visitExitCmdStmt(HyperTalkParser.ExitCmdStmtContext ctx) {
        return new ExitStatement(ctx, (String) visit(ctx.handlerName()));
    }

    @Override
    public Object visitExitToHyperCardCmdStmt(HyperTalkParser.ExitToHyperCardCmdStmtContext ctx) {
        return new ExitToHyperCardStatement(ctx);
    }

    @Override
    public Object visitPopCardCmdStmt(HyperTalkParser.PopCardCmdStmtContext ctx) {
        return new PopCardCmd(ctx);
    }

    @Override
    public Object visitPushCardCmdStmt(HyperTalkParser.PushCardCmdStmtContext ctx) {
        return new PushCardCmd(ctx);
    }

    @Override
    public Object visitPushDestCmdStmt(HyperTalkParser.PushDestCmdStmtContext ctx) {
        return new PushCardCmd(ctx, (DestinationExp) visit(ctx.destination()));
    }

    @Override
    public Object visitNoArgMsgCmdStmt(HyperTalkParser.NoArgMsgCmdStmtContext ctx) {
        return new MessageCmd(ctx, (String) visit(ctx.ID()), new ExpressionList());
    }

    @Override
    public Object visitArgMsgCmdStmt(HyperTalkParser.ArgMsgCmdStmtContext ctx) {
        return new MessageCmd(ctx, (String) visit(ctx.ID()), (ExpressionList) visit(ctx.argumentList()));
    }

    @Override
    public Object visitFindAnywhere(HyperTalkParser.FindAnywhereContext ctx) {
        return new FindCmd(ctx, (SearchType) visit(ctx.find()), (Expression) visit(ctx.factor()), false);
    }

    @Override
    public Object visitFindField(HyperTalkParser.FindFieldContext ctx) {
        return new FindCmd(ctx, (SearchType) visit(ctx.find()), (Expression) visit(ctx.factor()), (PartExp) visit(ctx.fieldPart()), false);
    }

    @Override
    public Object visitFindMarkedCards(HyperTalkParser.FindMarkedCardsContext ctx) {
        return new FindCmd(ctx, (SearchType) visit(ctx.find()), (Expression) visit(ctx.factor()), true);
    }

    @Override
    public Object visitFindFieldMarkedCards(HyperTalkParser.FindFieldMarkedCardsContext ctx) {
        return new FindCmd(ctx, (SearchType) visit(ctx.find()), (Expression) visit(ctx.factor()), (PartExp) visit(ctx.fieldPart()), true);
    }

    @Override
    public Object visitSearchableWord(HyperTalkParser.SearchableWordContext ctx) {
        return SearchType.WORDS;
    }

    @Override
    public Object visitSearchableChars(HyperTalkParser.SearchableCharsContext ctx) {
        return SearchType.CHARS;
    }

    @Override
    public Object visitSearchableWhole(HyperTalkParser.SearchableWholeContext ctx) {
        return SearchType.WHOLE;
    }

    @Override
    public Object visitSearchableString(HyperTalkParser.SearchableStringContext ctx) {
        return SearchType.STRING;
    }

    @Override
    public Object visitSearchableSubstring(HyperTalkParser.SearchableSubstringContext ctx) {
        return SearchType.SUBSTRING;
    }

    @Override
    public Object visitMusicInstrumentNotes(HyperTalkParser.MusicInstrumentNotesContext ctx) {
        return MusicSpecifier.forNotes((Expression) visit(ctx.factor()), (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitMusicInstrumentNotesTempo(HyperTalkParser.MusicInstrumentNotesTempoContext ctx) {
        return MusicSpecifier.forNotesAndTempo((Expression) visit(ctx.factor(0)), (Expression) visit(ctx.expression()), (Expression) visit(ctx.factor(1)));
    }

    @Override
    public Object visitMusicInstrumentTempo(HyperTalkParser.MusicInstrumentTempoContext ctx) {
        return MusicSpecifier.forTempo((Expression) visit(ctx.factor()), (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitSelectPartCmd(HyperTalkParser.SelectPartCmdContext ctx) {
        return new SelectPartCmd(ctx, (PartExp) visit(ctx.part()));
    }

    @Override
    public Object visitSelectEmptyCmd(HyperTalkParser.SelectEmptyCmdContext ctx) {
        return new SelectEmptyCmd(ctx);
    }

    @Override
    public Object visitSelectTextCmd(HyperTalkParser.SelectTextCmdContext ctx) {
        return new SelectTextCmd(ctx, Preposition.INTO, (PartExp) visit(ctx.part()));
    }

    @Override
    public Object visitSelectAfterChunkCmd(HyperTalkParser.SelectAfterChunkCmdContext ctx) {
        return new SelectTextCmd(ctx, Preposition.AFTER, (Chunk) visit(ctx.chunk()), (PartExp) visit(ctx.part()));
    }

    @Override
    public Object visitSelectBeforeChunkCmd(HyperTalkParser.SelectBeforeChunkCmdContext ctx) {
        return new SelectTextCmd(ctx, Preposition.BEFORE, (Chunk) visit(ctx.chunk()), (PartExp) visit(ctx.part()));
    }

    @Override
    public Object visitSelectAfterCmd(HyperTalkParser.SelectAfterCmdContext ctx) {
        return new SelectTextCmd(ctx, Preposition.AFTER, (PartExp) visit(ctx.part()));
    }

    @Override
    public Object visitSelectBeforeCmd(HyperTalkParser.SelectBeforeCmdContext ctx) {
        return new SelectTextCmd(ctx, Preposition.BEFORE, (PartExp) visit(ctx.part()));
    }

    @Override
    public Object visitSelectChunkCmd(HyperTalkParser.SelectChunkCmdContext ctx) {
        return new SelectTextCmd(ctx, Preposition.INTO, (Chunk) visit(ctx.chunk()), (PartExp) visit(ctx.part()));
    }

    @Override
    public Object visitWriteFileCmd(HyperTalkParser.WriteFileCmdContext ctx) {
        return WriteCmd.writeFile(ctx, (Expression) visit(ctx.expression()), (Expression) visit(ctx.factor()));
    }

    @Override
    public Object visitWriteEndFileCmd(HyperTalkParser.WriteEndFileCmdContext ctx) {
        return WriteCmd.appendFile(ctx, (Expression) visit(ctx.expression()), (Expression) visit(ctx.factor()));
    }

    @Override
    public Object visitWriteAtFileCmd(HyperTalkParser.WriteAtFileCmdContext ctx) {
        return WriteCmd.writeFileAt(ctx, (Expression) visit(ctx.expression()), (Expression) visit(ctx.factor(0)), (Expression) visit(ctx.factor(1)));
    }

    @Override
    public Object visitReadFileCmd(HyperTalkParser.ReadFileCmdContext ctx) {
        return ReadCmd.ofFile(ctx, (Expression) visit(ctx.factor()));
    }

    @Override
    public Object visitReadFileForCmd(HyperTalkParser.ReadFileForCmdContext ctx) {
        return ReadCmd.ofFileFor(ctx, (Expression) visit(ctx.factor(0)), (Expression) visit(ctx.factor(1)));
    }

    @Override
    public Object visitReadFileAtCmd(HyperTalkParser.ReadFileAtCmdContext ctx) {
        return ReadCmd.ofFileAt(ctx, (Expression) visit(ctx.factor(0)), (Expression) visit(ctx.factor(1)), (Expression) visit(ctx.factor(2)));
    }

    @Override
    public Object visitReadFileUntil(HyperTalkParser.ReadFileUntilContext ctx) {
        return ReadCmd.ofFileUntil(ctx, (Expression) visit(ctx.factor(0)), (Expression) visit(ctx.factor(1)));
    }

    @Override
    public Object visitMusicInstrument(HyperTalkParser.MusicInstrumentContext ctx) {
        return MusicSpecifier.forDefault((Expression) visit(ctx.factor()));
    }

    @Override
    public Object visitLockScreenCmdStmt(HyperTalkParser.LockScreenCmdStmtContext ctx) {
        return new SetPropertyCmd(ctx, HyperCardProperties.PROP_LOCKSCREEN, new Value(true));
    }

    @Override
    public Object visitUnlockScreenCmdStmt(HyperTalkParser.UnlockScreenCmdStmtContext ctx) {
        return new SetPropertyCmd(ctx, HyperCardProperties.PROP_LOCKSCREEN, new Value(false));
    }

    @Override
    public Object visitUnlockScreenVisualCmdStmt(HyperTalkParser.UnlockScreenVisualCmdStmtContext ctx) {
        return new UnlockScreenCmd(ctx, (VisualEffectSpecifier) visit(ctx.visualEffect()));
    }

    @Override
    public Object visitPassCmdStmt(HyperTalkParser.PassCmdStmtContext ctx) {
        return new PassCmd(ctx, (String) visit(ctx.handlerName()));
    }

    @Override
    public Object visitDoMenuCmdStmt(HyperTalkParser.DoMenuCmdStmtContext ctx) {
        return new DoMenuCmd(ctx, (Expression) visit(ctx.factor()));
    }

    @Override
    public Object visitVisualEffectCmdStmt(HyperTalkParser.VisualEffectCmdStmtContext ctx) {
        return new VisualEffectCmd(ctx, (VisualEffectSpecifier) visit(ctx.visualEffect()));
    }

    @Override
    public Object visitResetMenuCmdStmt(HyperTalkParser.ResetMenuCmdStmtContext ctx) {
        return new ResetMenuCmd(ctx);
    }

    @Override
    public Object visitResetPaintCmdStmt(HyperTalkParser.ResetPaintCmdStmtContext ctx) {
        return new ResetPaintCmd(ctx);
    }

    @Override
    public Object visitCreateMenuCmdStmt(HyperTalkParser.CreateMenuCmdStmtContext ctx) {
        return new CreateMenuCmd(ctx, (Expression) visit(ctx.factor()));
    }

    @Override
    public Object visitDeleteMenuCmdStmt(HyperTalkParser.DeleteMenuCmdStmtContext ctx) {
        return new DeleteMenuCmd(ctx, (MenuSpecifier) visit(ctx.menu()));
    }

    @Override
    public Object visitDeleteMenuItemCmdStmt(HyperTalkParser.DeleteMenuItemCmdStmtContext ctx) {
        return new DeleteMenuItemCmd(ctx, (MenuItemSpecifier) visit(ctx.menuItem()));
    }

    @Override
    public Object visitEnablePartCmd(HyperTalkParser.EnablePartCmdContext ctx) {
        return new SetPropertyCmd(ctx, (PartExp) visit(ctx.part()), CardLayerPartModel.PROP_ENABLED, new Value(true));
    }

    @Override
    public Object visitEnableMenuItemCmd(HyperTalkParser.EnableMenuItemCmdContext ctx) {
        return new EnableMenuItemCmd(ctx, (MenuItemSpecifier) visit(ctx.menuItem()), true);
    }

    @Override
    public Object visitEnableMenuCmd(HyperTalkParser.EnableMenuCmdContext ctx) {
        return new EnableMenuCmd(ctx, (MenuSpecifier) visit(ctx.menu()), true);
    }

    @Override
    public Object visitDisablePartCmd(HyperTalkParser.DisablePartCmdContext ctx) {
        return new SetPropertyCmd(ctx, (PartExp) visit(ctx.part()), CardLayerPartModel.PROP_ENABLED, new Value(false));
    }

    @Override
    public Object visitDisableMenuItemCmd(HyperTalkParser.DisableMenuItemCmdContext ctx) {
        return new EnableMenuItemCmd(ctx, (MenuItemSpecifier) visit(ctx.menuItem()), false);
    }

    @Override
    public Object visitDisableMenuCmd(HyperTalkParser.DisableMenuCmdContext ctx) {
        return new EnableMenuCmd(ctx, (MenuSpecifier) visit(ctx.menu()), false);
    }

    @Override
    public Object visitIfStatement(HyperTalkParser.IfStatementContext ctx) {
        return new IfStatement(ctx, (Expression) visit(ctx.expression()), (ThenElseBlock) visit(ctx.thenStatement()));
    }

    @Override
    public Object visitThenSingleLineStmnt(HyperTalkParser.ThenSingleLineStmntContext ctx) {
        return new ThenElseBlock((Statement) visit(ctx.statement()), null);
    }

    @Override
    public Object visitThenSingleStmnt(HyperTalkParser.ThenSingleStmntContext ctx) {
        return new ThenElseBlock((Statement) visit(ctx.statement()), ctx.elseStatement() == null ? null : (Statement) visit(ctx.elseStatement()));
    }

    @Override
    public Object visitThenStmntList(HyperTalkParser.ThenStmntListContext ctx) {
        return new ThenElseBlock((Statement) visit(ctx.statementList()), ctx.elseStatement() == null ? null : (Statement) visit(ctx.elseStatement()));
    }

    @Override
    public Object visitElseSingleStmt(HyperTalkParser.ElseSingleStmtContext ctx) {
        return visit(ctx.statement());
    }

    @Override
    public Object visitElseStmntList(HyperTalkParser.ElseStmntListContext ctx) {
        return visit(ctx.statementList());
    }

    @Override
    public Object visitRepeatStmntList(HyperTalkParser.RepeatStmntListContext ctx) {
        return new RepeatStatement(ctx, (RepeatSpecifier) visit(ctx.repeatRange()), (StatementList) visit(ctx.statementList()));
    }

    @Override
    public Object visitRepeatEmpty(HyperTalkParser.RepeatEmptyContext ctx) {
        return new RepeatStatement(ctx, (RepeatSpecifier) visit(ctx.repeatRange()), new StatementList(ctx));
    }

    @Override
    public Object visitInfiniteLoop(HyperTalkParser.InfiniteLoopContext ctx) {
        return new RepeatForever();
    }

    @Override
    public Object visitDurationLoop(HyperTalkParser.DurationLoopContext ctx) {
        return visit(ctx.duration());
    }

    @Override
    public Object visitCountLoop(HyperTalkParser.CountLoopContext ctx) {
        return visit(ctx.count());
    }

    @Override
    public Object visitWithLoop(HyperTalkParser.WithLoopContext ctx) {
        return new RepeatWith((String) visit(ctx.ID()), (RepeatRange) visit(ctx.range()));
    }

    @Override
    public Object visitUntilDuration(HyperTalkParser.UntilDurationContext ctx) {
        return new RepeatDuration(RepeatDuration.POLARITY_UNTIL, (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitWhileDuration(HyperTalkParser.WhileDurationContext ctx) {
        return new RepeatDuration(RepeatDuration.POLARITY_WHILE, (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitCount(HyperTalkParser.CountContext ctx) {
        return new RepeatCount((Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitRangeDownTo(HyperTalkParser.RangeDownToContext ctx) {
        return new RepeatRange(RepeatRange.POLARITY_DOWNTO, (Expression) visit(ctx.expression(0)), (Expression) visit(ctx.expression(1)));
    }

    @Override
    public Object visitRangeUpTo(HyperTalkParser.RangeUpToContext ctx) {
        return new RepeatRange(RepeatRange.POLARITY_UPTO, (Expression) visit(ctx.expression(0)), (Expression) visit(ctx.expression(1)));
    }

    @Override
    public Object visitGlobalStmnt(HyperTalkParser.GlobalStmntContext ctx) {
        return new GlobalStatement(ctx, (ParameterList) visit(ctx.parameterList()));
    }

    @Override
    public Object visitAnswerThreeButtonCmd(HyperTalkParser.AnswerThreeButtonCmdContext ctx) {
        return new AnswerCmd(ctx, (Expression) visit(ctx.expression()), (Expression) visit(ctx.factor(0)), (Expression) visit(ctx.factor(1)), (Expression) visit(ctx.factor(2)));
    }

    @Override
    public Object visitAnswerTwoButtonCmd(HyperTalkParser.AnswerTwoButtonCmdContext ctx) {
        return new AnswerCmd(ctx, (Expression) visit(ctx.expression()), (Expression) visit(ctx.factor(0)), (Expression) visit(ctx.factor(1)));
    }

    @Override
    public Object visitAnswerOneButtonCmd(HyperTalkParser.AnswerOneButtonCmdContext ctx) {
        return new AnswerCmd(ctx, (Expression) visit(ctx.expression()), (Expression) visit(ctx.factor()));
    }

    @Override
    public Object visitAnswerDefaultCmd(HyperTalkParser.AnswerDefaultCmdContext ctx) {
        return new AnswerCmd(ctx, (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitAskExpWithCmd(HyperTalkParser.AskExpWithCmdContext ctx) {
        return new AskCmd(ctx, (Expression) visit(ctx.expression(0)), (Expression) visit(ctx.expression(1)));
    }

    @Override
    public Object visitAskExpCmd(HyperTalkParser.AskExpCmdContext ctx) {
        return new AskCmd(ctx, (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitPutIntoCmd(HyperTalkParser.PutIntoCmdContext ctx) {
        return new PutCmd(ctx, (Expression) visit(ctx.expression()), Preposition.INTO, new MsgBoxContainer());
    }

    @Override
    public Object visitPutPrepositionCmd(HyperTalkParser.PutPrepositionCmdContext ctx) {
        return new PutCmd(ctx, (Expression) visit(ctx.expression()), (Preposition) visit(ctx.preposition()), (Container) visit(ctx.container()));
    }

    @Override
    public Object visitBeforePreposition(HyperTalkParser.BeforePrepositionContext ctx) {
        return Preposition.BEFORE;
    }

    @Override
    public Object visitAfterPreposition(HyperTalkParser.AfterPrepositionContext ctx) {
        return Preposition.AFTER;
    }

    @Override
    public Object visitIntoPreposition(HyperTalkParser.IntoPrepositionContext ctx) {
        return Preposition.INTO;
    }

    @Override
    public Object visitVariableDest(HyperTalkParser.VariableDestContext ctx) {
        return new VariableContainer((String) visit(ctx.ID()));
    }

    @Override
    public Object visitCompositeChunk(HyperTalkParser.CompositeChunkContext ctx) {
        Chunk lChunk = (Chunk) visit(ctx.chunk(0));
        Chunk rChunk = (Chunk) visit(ctx.chunk(1));
        return new CompositeChunk(rChunk.type, rChunk.start, rChunk.end, lChunk);
    }

    @Override
    public Object visitPartDest(HyperTalkParser.PartDestContext ctx) {
        return new PartContainer((PartExp) visit(ctx.part()));
    }

    @Override
    public Object visitMessage(HyperTalkParser.MessageContext ctx) {
        return super.visitMessage(ctx);
    }

    @Override
    public Object visitCards(HyperTalkParser.CardsContext ctx) {
        return super.visitCards(ctx);
    }

    @Override
    public Object visitSelectionDest(HyperTalkParser.SelectionDestContext ctx) {
        return new SelectionContainer();
    }

    @Override
    public Object visitExpressionMenu(HyperTalkParser.ExpressionMenuContext ctx) {
        return new MenuSpecifier((Expression) visit(ctx.factor()));
    }

    @Override
    public Object visitOrdinalMenu(HyperTalkParser.OrdinalMenuContext ctx) {
        return new MenuSpecifier((Ordinal) visit(ctx.ordinal()));
    }

    @Override
    public Object visitExpressionMenuItem(HyperTalkParser.ExpressionMenuItemContext ctx) {
        return new MenuItemSpecifier((Expression) visit(ctx.factor()), (MenuSpecifier) visit(ctx.menu()));
    }

    @Override
    public Object visitOrdinalMenuItem(HyperTalkParser.OrdinalMenuItemContext ctx) {
        return new MenuItemSpecifier((Ordinal) visit(ctx.ordinal()), (MenuSpecifier) visit(ctx.menu()));
    }

    @Override
    public Object visitPropertyValueLiteral(HyperTalkParser.PropertyValueLiteralContext ctx) {
        return new LiteralExp(ctx, ctx.getText());
    }

    @Override
    public Object visitPropertyValueExp(HyperTalkParser.PropertyValueExpContext ctx) {
        return visit(ctx.expression());
    }

    @Override
    public Object visitPropertySpecGlobal(HyperTalkParser.PropertySpecGlobalContext ctx) {
        return new PropertySpecifier((String) visit(ctx.propertyName()));
    }

    @Override
    public Object visitPropertySpecPart(HyperTalkParser.PropertySpecPartContext ctx) {
        return new PropertySpecifier((String) visit(ctx.propertyName()), (PartExp) visit(ctx.part()));
    }

    @Override
    public Object visitPropertySpecChunkPart(HyperTalkParser.PropertySpecChunkPartContext ctx) {
        return new PropertySpecifier((String) visit(ctx.propertyName()), (Chunk) visit(ctx.chunk()), (PartExp) visit(ctx.part()));
    }

    @Override
    public Object visitPropertySpecMenuItem(HyperTalkParser.PropertySpecMenuItemContext ctx) {
        return new PropertySpecifier((String) visit(ctx.propertyName()), (MenuItemSpecifier) visit(ctx.menuItem()));
    }

    @Override
    public Object visitPropertyName(HyperTalkParser.PropertyNameContext ctx) {
        return ctx.getText();
    }

    @Override
    public Object visitCommandName(HyperTalkParser.CommandNameContext ctx) {
        return super.visitCommandName(ctx);
    }

    @Override
    public Object visitButtonPartPart(HyperTalkParser.ButtonPartPartContext ctx) {
        return visit(ctx.buttonPart());
    }

    @Override
    public Object visitFieldPartPart(HyperTalkParser.FieldPartPartContext ctx) {
        return visit(ctx.fieldPart());
    }

    @Override
    public Object visitBkgndPartPart(HyperTalkParser.BkgndPartPartContext ctx) {
        return visit(ctx.bkgndPart());
    }

    @Override
    public Object visitCardPartPart(HyperTalkParser.CardPartPartContext ctx) {
        return visit(ctx.cardPart());
    }

    @Override
    public Object visitBkgndFieldPart(HyperTalkParser.BkgndFieldPartContext ctx) {
        return new PartNameExp(ctx, Owner.BACKGROUND, PartType.FIELD, (Expression)visit(ctx.factor()));
    }

    @Override
    public Object visitBkgndFieldOrdinalPart(HyperTalkParser.BkgndFieldOrdinalPartContext ctx) {
        return new PartNumberExp(ctx, Owner.BACKGROUND, PartType.FIELD, (Ordinal) visit(ctx.ordinal()));
    }

    @Override
    public Object visitBkgndFieldIdPart(HyperTalkParser.BkgndFieldIdPartContext ctx) {
        return new PartIdExp(ctx, Owner.BACKGROUND, PartType.FIELD, (Expression)visit(ctx.factor()));
    }

    @Override
    public Object visitBkgndButtonPart(HyperTalkParser.BkgndButtonPartContext ctx) {
        return new PartNameExp(ctx, Owner.BACKGROUND, PartType.BUTTON, (Expression)visit(ctx.factor()));
    }

    @Override
    public Object visitButtonOfCardPart(HyperTalkParser.ButtonOfCardPartContext ctx) {
        return new RemotePartExp(ctx, (PartExp) visit(ctx.buttonPart()), (PartExp) visit(ctx.cardPart()));
    }

    @Override
    public Object visitBkgndButtonOrdinalPart(HyperTalkParser.BkgndButtonOrdinalPartContext ctx) {
        return new PartNumberExp(ctx, Owner.BACKGROUND, PartType.BUTTON, (Ordinal) visit(ctx.ordinal()));
    }

    @Override
    public Object visitBkgndButtonIdPart(HyperTalkParser.BkgndButtonIdPartContext ctx) {
        return new PartIdExp(ctx, Owner.BACKGROUND, PartType.BUTTON, (Expression)visit(ctx.factor()));
    }

    @Override
    public Object visitCardFieldPart(HyperTalkParser.CardFieldPartContext ctx) {
        return new PartNameExp(ctx, Owner.CARD, PartType.FIELD, (Expression)visit(ctx.factor()));
    }

    @Override
    public Object visitFieldOfCardPart(HyperTalkParser.FieldOfCardPartContext ctx) {
        return new RemotePartExp(ctx, (PartExp) visit(ctx.fieldPart()), (PartExp) visit(ctx.cardPart()));
    }

    @Override
    public Object visitCardFieldOrdinalPart(HyperTalkParser.CardFieldOrdinalPartContext ctx) {
        return new PartNumberExp(ctx, Owner.CARD, PartType.FIELD, (Ordinal) visit(ctx.ordinal()));
    }

    @Override
    public Object visitCardFieldIdPart(HyperTalkParser.CardFieldIdPartContext ctx) {
        return new PartIdExp(ctx, Owner.CARD, PartType.FIELD, (Expression)visit(ctx.factor()));
    }

    @Override
    public Object visitCardButtonPart(HyperTalkParser.CardButtonPartContext ctx) {
        return new PartNameExp(ctx, Owner.CARD, PartType.BUTTON, (Expression)visit(ctx.factor()));
    }

    @Override
    public Object visitCardButtonOrdinalPart(HyperTalkParser.CardButtonOrdinalPartContext ctx) {
        return new PartNumberExp(ctx, Owner.CARD, PartType.BUTTON, (Ordinal) visit(ctx.ordinal()));
    }

    @Override
    public Object visitCardButtonIdPart(HyperTalkParser.CardButtonIdPartContext ctx) {
        return new PartIdExp(ctx, Owner.CARD, PartType.BUTTON, (Expression)visit(ctx.factor()));
    }

    @Override
    public Object visitCardPartNumberPart(HyperTalkParser.CardPartNumberPartContext ctx) {
        return new PartNumberExp(ctx, Owner.CARD, (Expression)visit(ctx.factor()));
    }

    @Override
    public Object visitBkgndPartNumberPart(HyperTalkParser.BkgndPartNumberPartContext ctx) {
        return new PartNumberExp(ctx, Owner.BACKGROUND, (Expression)visit(ctx.factor()));
    }

    @Override
    public Object visitMePart(HyperTalkParser.MePartContext ctx) {
        return new PartMeExp(ctx);
    }

    @Override
    public Object visitMsgPart(HyperTalkParser.MsgPartContext ctx) {
        return new PartMessageExp(ctx);
    }

    @Override
    public Object visitPartRef(HyperTalkParser.PartRefContext ctx) {
        return new PartReferenceExp(ctx, ctx.ID().getText());
    }

    @Override
    public Object visitCard(HyperTalkParser.CardContext ctx) {
        return super.visitCard(ctx);
    }

    @Override
    public Object visitBackground(HyperTalkParser.BackgroundContext ctx) {
        return super.visitBackground(ctx);
    }

    @Override
    public Object visitButton(HyperTalkParser.ButtonContext ctx) {
        return super.visitButton(ctx);
    }

    @Override
    public Object visitField(HyperTalkParser.FieldContext ctx) {
        return super.visitField(ctx);
    }

    @Override
    public Object visitCharacter(HyperTalkParser.CharacterContext ctx) {
        return super.visitCharacter(ctx);
    }

    @Override
    public Object visitWord(HyperTalkParser.WordContext ctx) {
        return super.visitWord(ctx);
    }

    @Override
    public Object visitLine(HyperTalkParser.LineContext ctx) {
        return super.visitLine(ctx);
    }

    @Override
    public Object visitItem(HyperTalkParser.ItemContext ctx) {
        return super.visitItem(ctx);
    }

    @Override
    public Object visitOf(HyperTalkParser.OfContext ctx) {
        return super.visitOf(ctx);
    }

    @Override
    public Object visitThisCardPart(HyperTalkParser.ThisCardPartContext ctx) {
        return new PartPositionExp(ctx, PartType.CARD, Position.THIS);
    }

    @Override
    public Object visitThisBkgndPart(HyperTalkParser.ThisBkgndPartContext ctx) {
        return new PartPositionExp(ctx, PartType.BACKGROUND, Position.THIS);
    }

    @Override
    public Object visitPositionCardPart(HyperTalkParser.PositionCardPartContext ctx) {
        return new PartPositionExp(ctx, PartType.CARD, (Position) visit(ctx.position()));
    }

    @Override
    public Object visitCardOfBkgndPart(HyperTalkParser.CardOfBkgndPartContext ctx) {
        return new RemotePartExp(ctx, (PartExp) visit(ctx.cardPart()), (PartExp) visit(ctx.bkgndPart()));
    }

    @Override
    public Object visitPositionBkgndPart(HyperTalkParser.PositionBkgndPartContext ctx) {
        return new PartPositionExp(ctx, PartType.BACKGROUND, (Position) visit(ctx.position()));
    }

    @Override
    public Object visitOrdinalCardPart(HyperTalkParser.OrdinalCardPartContext ctx) {
        return new PartNumberExp(ctx, PartType.CARD, (Ordinal) visit(ctx.ordinal()));
    }

    @Override
    public Object visitOrdinalBkgndPart(HyperTalkParser.OrdinalBkgndPartContext ctx) {
        return new PartNumberExp(ctx, PartType.BACKGROUND, (Ordinal) visit(ctx.ordinal()));
    }

    @Override
    public Object visitExpressionCardPart(HyperTalkParser.ExpressionCardPartContext ctx) {
        return new PartNameExp(ctx, PartType.CARD, (Expression) visit(ctx.factor()));
    }

    @Override
    public Object visitCardIdPart(HyperTalkParser.CardIdPartContext ctx) {
        return new PartIdExp(ctx, PartType.CARD, (Expression) visit(ctx.factor()));
    }

    @Override
    public Object visitExpressionBkgndPart(HyperTalkParser.ExpressionBkgndPartContext ctx) {
        return new PartNameExp(ctx, PartType.BACKGROUND, (Expression) visit(ctx.factor()));
    }

    @Override
    public Object visitBkgndIdPart(HyperTalkParser.BkgndIdPartContext ctx) {
        return new PartIdExp(ctx, PartType.BACKGROUND, (Expression) visit(ctx.factor()));
    }

    @Override
    public Object visitOrdinalCharChunk(HyperTalkParser.OrdinalCharChunkContext ctx) {
        return new Chunk(ChunkType.CHAR, new LiteralExp(ctx, ((Ordinal) visit(ctx.ordinal())).stringValue()));
    }

    @Override
    public Object visitRangeCharChunk(HyperTalkParser.RangeCharChunkContext ctx) {
        return new Chunk(ChunkType.CHARRANGE, (Expression) visit(ctx.expression(0)), (Expression) visit(ctx.expression(1)));
    }

    @Override
    public Object visitCharCharChunk(HyperTalkParser.CharCharChunkContext ctx) {
        return new Chunk(ChunkType.CHAR, (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitOrdinalWordChunk(HyperTalkParser.OrdinalWordChunkContext ctx) {
        return new Chunk(ChunkType.WORD, new LiteralExp(ctx, ((Ordinal) visit(ctx.ordinal())).stringValue()));
    }

    @Override
    public Object visitRangeWordChunk(HyperTalkParser.RangeWordChunkContext ctx) {
        return new Chunk(ChunkType.WORDRANGE, (Expression) visit(ctx.expression(0)), (Expression) visit(ctx.expression(1)));
    }

    @Override
    public Object visitWordWordChunk(HyperTalkParser.WordWordChunkContext ctx) {
        return new Chunk(ChunkType.WORD, (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitOrdinalItemChunk(HyperTalkParser.OrdinalItemChunkContext ctx) {
        return new Chunk(ChunkType.ITEM, new LiteralExp(ctx, ((Ordinal) visit(ctx.ordinal())).stringValue()));
    }

    @Override
    public Object visitRangeItemChunk(HyperTalkParser.RangeItemChunkContext ctx) {
        return new Chunk(ChunkType.ITEMRANGE, (Expression) visit(ctx.expression(0)), (Expression) visit(ctx.expression(1)));
    }

    @Override
    public Object visitItemItemChunk(HyperTalkParser.ItemItemChunkContext ctx) {
        return new Chunk(ChunkType.ITEM, (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitOrdinalLineChunk(HyperTalkParser.OrdinalLineChunkContext ctx) {
        return new Chunk(ChunkType.LINE, new LiteralExp(ctx, ((Ordinal) visit(ctx.ordinal())).stringValue()));
    }

    @Override
    public Object visitRangeLineChunk(HyperTalkParser.RangeLineChunkContext ctx) {
        return new Chunk(ChunkType.LINERANGE, (Expression) visit(ctx.expression(0)), (Expression) visit(ctx.expression(1)));
    }

    @Override
    public Object visitLineLineChunk(HyperTalkParser.LineLineChunkContext ctx) {
        return new Chunk(ChunkType.LINE, (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitMultiplicationExp(HyperTalkParser.MultiplicationExpContext ctx) {
        return new BinaryOperatorExp(ctx, (Expression) visit(ctx.expression(0)), BinaryOperator.fromName(ctx.op.getText()), (Expression) visit(ctx.expression(1)));
    }

    @Override
    public Object visitOrExp(HyperTalkParser.OrExpContext ctx) {
        return new BinaryOperatorExp(ctx, (Expression) visit(ctx.expression(0)), BinaryOperator.OR, (Expression) visit(ctx.expression(1)));
    }

    @Override
    public Object visitAndExp(HyperTalkParser.AndExpContext ctx) {
        return new BinaryOperatorExp(ctx, (Expression) visit(ctx.expression(0)), BinaryOperator.AND, (Expression) visit(ctx.expression(1)));
    }

    @Override
    public Object visitEqualityExp(HyperTalkParser.EqualityExpContext ctx) {
        return new BinaryOperatorExp(ctx, (Expression) visit(ctx.expression(0)), BinaryOperator.fromName(ctx.op.getText()), (Expression) visit(ctx.expression(1)));
    }

    @Override
    public Object visitCaratExp(HyperTalkParser.CaratExpContext ctx) {
        return new BinaryOperatorExp(ctx, (Expression) visit(ctx.expression(0)), BinaryOperator.EXP, (Expression) visit(ctx.expression(1)));
    }

    @Override
    public Object visitComparisonExp(HyperTalkParser.ComparisonExpContext ctx) {
        return new BinaryOperatorExp(ctx, (Expression) visit(ctx.expression(0)), BinaryOperator.fromName(ctx.op.getText()), (Expression) visit(ctx.expression(1)));
    }

    @Override
    public Object visitAdditionExp(HyperTalkParser.AdditionExpContext ctx) {
        return new BinaryOperatorExp(ctx, (Expression) visit(ctx.expression(0)), BinaryOperator.fromName(ctx.op.getText()), (Expression) visit(ctx.expression(1)));
    }

    @Override
    public Object visitFunctionExp(HyperTalkParser.FunctionExpContext ctx) {
        return visit(ctx.functionCall());
    }

    @Override
    public Object visitNegateExp(HyperTalkParser.NegateExpContext ctx) {
        return new UnaryOperatorExp(ctx, UnaryOperator.NEGATE, (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitNotExp(HyperTalkParser.NotExpContext ctx) {
        return new UnaryOperatorExp(ctx, UnaryOperator.NOT, (Expression) visit(ctx.expression()));
    }

    @Override
    public Object visitFactorExp(HyperTalkParser.FactorExpContext ctx) {
        return visit(ctx.factor());
    }

    @Override
    public Object visitUserArgFuncCall(HyperTalkParser.UserArgFuncCallContext ctx) {
        ExpressionList args = ctx.argumentList() == null ? new ExpressionList(ctx) : (ExpressionList) visit(ctx.argumentList());
        return new UserFunctionExp(ctx, (String) visit(ctx.ID()), args);
    }

    @Override
    public Object visitMouseFunc(HyperTalkParser.MouseFuncContext ctx) {
        return BuiltInFunction.MOUSE;
    }

    @Override
    public Object visitMouseLocFunc(HyperTalkParser.MouseLocFuncContext ctx) {
        return BuiltInFunction.MOUSELOC;
    }

    @Override
    public Object visitResultFunc(HyperTalkParser.ResultFuncContext ctx) {
        return BuiltInFunction.RESULT;
    }

    @Override
    public Object visitOptionKeyFunc(HyperTalkParser.OptionKeyFuncContext ctx) {
        return BuiltInFunction.OPTION_KEY;
    }

    @Override
    public Object visitShiftKeyFunc(HyperTalkParser.ShiftKeyFuncContext ctx) {
        return BuiltInFunction.SHIFT_KEY;
    }

    @Override
    public Object visitCommandKeyFunc(HyperTalkParser.CommandKeyFuncContext ctx) {
        return BuiltInFunction.COMMAND_KEY;
    }

    @Override
    public Object visitTicksFunc(HyperTalkParser.TicksFuncContext ctx) {
        return BuiltInFunction.TICKS;
    }

    @Override
    public Object visitSecondsFunc(HyperTalkParser.SecondsFuncContext ctx) {
        return BuiltInFunction.SECONDS;
    }

    @Override
    public Object visitTimeFunc(HyperTalkParser.TimeFuncContext ctx) {
        return ((DateLength) visit(ctx.timeDateFormat())).getTimeFunction();
    }

    @Override
    public Object visitDateFunc(HyperTalkParser.DateFuncContext ctx) {
        return ((DateLength) visit(ctx.timeDateFormat())).getDateFunction();
    }

    @Override
    public Object visitToolFunc(HyperTalkParser.ToolFuncContext ctx) {
        return BuiltInFunction.TOOL;
    }

    @Override
    public Object visitLiteralFactor(HyperTalkParser.LiteralFactorContext ctx) {
        return new LiteralExp(ctx, visit(ctx.literal()));
    }

    @Override
    public Object visitIdFactor(HyperTalkParser.IdFactorContext ctx) {
        return new VariableExp(ctx, (String) visit(ctx.ID()));
    }

    @Override
    public Object visitPartFactor(HyperTalkParser.PartFactorContext ctx) {
        return visit(ctx.part());
    }

    @Override
    public Object visitSelectionFactor(HyperTalkParser.SelectionFactorContext ctx) {
        return new SelectionExp(ctx);
    }

    @Override
    public Object visitExpressionFactor(HyperTalkParser.ExpressionFactorContext ctx) {
        return visit(ctx.expression());
    }

    @Override
    public Object visitProperty(HyperTalkParser.PropertyContext ctx) {
        return super.visitProperty(ctx);
    }

    @Override
    public Object visitPartPropertyFactor(HyperTalkParser.PartPropertyFactorContext ctx) {
        return new PropertyExp(ctx, (PropertySpecifier) visit(ctx.property()));
    }

    @Override
    public Object visitMenuFactor(HyperTalkParser.MenuFactorContext ctx) {
        return new MenuExp(ctx, (MenuSpecifier) visit(ctx.menu()));
    }

    @Override
    public Object visitMenuItemFactor(HyperTalkParser.MenuItemFactorContext ctx) {
        return new MenuExp(ctx, (MenuItemSpecifier) visit(ctx.menuItem()));
    }

    @Override
    public Object visitChunkFactorChunk(HyperTalkParser.ChunkFactorChunkContext ctx) {
        return new ChunkExp(ctx, (Chunk) visit(ctx.chunk()), (Expression) visit(ctx.factor()));
    }

    @Override
    public Object visitTruncFunc(HyperTalkParser.TruncFuncContext ctx) {
        return BuiltInFunction.TRUNC;
    }

    @Override
    public Object visitEmptyExp(HyperTalkParser.EmptyExpContext ctx) {
        return new Value("");
    }

    @Override
    public Object visitPiExp(HyperTalkParser.PiExpContext ctx) {
        return new Value("3.14159265358979323846");
    }

    @Override
    public Object visitQuoteExp(HyperTalkParser.QuoteExpContext ctx) {
        return new Value("\"");
    }

    @Override
    public Object visitReturnExp(HyperTalkParser.ReturnExpContext ctx) {
        return new Value("\n");
    }

    @Override
    public Object visitSpaceExp(HyperTalkParser.SpaceExpContext ctx) {
        return new Value(" ");
    }

    @Override
    public Object visitTabExp(HyperTalkParser.TabExpContext ctx) {
        return new Value("\t");
    }

    @Override
    public Object visitFormFeedExp(HyperTalkParser.FormFeedExpContext ctx) {
        return new Value("\f");
    }

    @Override
    public Object visitLineFeedExp(HyperTalkParser.LineFeedExpContext ctx) {
        return new Value("\n");
    }

    @Override
    public Object visitCommaExp(HyperTalkParser.CommaExpContext ctx) {
        return new Value(",");
    }

    @Override
    public Object visitColonExp(HyperTalkParser.ColonExpContext ctx) {
        return new Value(":");
    }

    @Override
    public Object visitCardinalValue(HyperTalkParser.CardinalValueContext ctx) {
        return super.visitCardinalValue(ctx);
    }

    @Override
    public Object visitCardninalExp(HyperTalkParser.CardninalExpContext ctx) {
        return LiteralExp.ofCardinal(ctx, ctx.getText());
    }

    @Override
    public Object visitConcatExp(HyperTalkParser.ConcatExpContext ctx) {
        return new BinaryOperatorExp(ctx, (Expression) visit(ctx.expression(0)), BinaryOperator.fromName(ctx.op.getText()), (Expression) visit(ctx.expression(1)));
    }

    @Override
    public Object visitWaitForCountCmd(HyperTalkParser.WaitForCountCmdContext ctx) {
        return new WaitCmd(ctx, (Expression) visit(ctx.factor()), (TimeUnit) visit(ctx.timeUnit()));
    }

    @Override
    public Object visitTickTimeUnit(HyperTalkParser.TickTimeUnitContext ctx) {
        return TimeUnit.TICKS;
    }

    @Override
    public Object visitSecTimeUnit(HyperTalkParser.SecTimeUnitContext ctx) {
        return TimeUnit.SECONDS;
    }

    @Override
    public Object visitSecondTimeUnit(HyperTalkParser.SecondTimeUnitContext ctx) {
        return TimeUnit.SECONDS;
    }

    @Override
    public Object visitTheOrdinalVal(HyperTalkParser.TheOrdinalValContext ctx) {
        return Ordinal.fromHyperTalkIdentifier(ctx.ordinalValue().getText());
    }

    @Override
    public Object visitOrdinalValue(HyperTalkParser.OrdinalValueContext ctx) {
        return super.visitOrdinalValue(ctx);
    }

    @Override
    public Object visitMouseState(HyperTalkParser.MouseStateContext ctx) {
        return super.visitMouseState(ctx);
    }

    @Override
    public Object visitModifierKey(HyperTalkParser.ModifierKeyContext ctx) {
        return super.visitModifierKey(ctx);
    }

    @Override
    public Object visitKnownType(HyperTalkParser.KnownTypeContext ctx) {
        return super.visitKnownType(ctx);
    }

    @Override
    public Object visitBuiltInFuncCall(HyperTalkParser.BuiltInFuncCallContext ctx) {
        return visit(ctx.builtInFunc());
    }

    @Override
    public Object visitBuiltinFuncOneArgs(HyperTalkParser.BuiltinFuncOneArgsContext ctx) {
        switch ((BuiltInFunction) visit(ctx.singleArgFunc())) {
            case MIN: return new MinFunc(ctx, (Expression) visit(ctx.factor()));
            case MAX: return new MaxFunc(ctx, (Expression) visit(ctx.factor()));
            case SUM: return new SumFunc(ctx, (Expression) visit(ctx.factor()));
            case AVERAGE: return new AverageFunc(ctx, (Expression) visit(ctx.factor()));
            case NUMBER_CHARS: return new NumberOfFunc(ctx, Countable.CHAR, (Expression) visit(ctx.factor()));
            case NUMBER_ITEMS: return new NumberOfFunc(ctx, Countable.ITEM, (Expression) visit(ctx.factor()));
            case NUMBER_LINES: return new NumberOfFunc(ctx, Countable.LINE, (Expression) visit(ctx.factor()));
            case NUMBER_WORDS: return new NumberOfFunc(ctx, Countable.WORD, (Expression) visit(ctx.factor()));
            case NUMBER_MENUITEMS: return new NumberOfFunc(ctx, Countable.MENU_ITEMS, (Expression) visit(ctx.factor()));
            case NUMBER_BKGND_CARDS: return new NumberOfFunc(ctx, Countable.CARDS_IN_BKGND, (Expression) visit(ctx.factor()));
            case RANDOM: return new RandomFunc(ctx, (Expression) visit(ctx.factor()));
            case SQRT:
            case TRUNC:
            case SIN:
            case COS:
            case TAN:
            case ATAN:
            case EXP:
            case EXP1:
            case EXP2:
            case LN:
            case LN1:
            case LOG2:
            case ABS:
            case NUM_TO_CHAR:
                return new MathFunc(ctx, (BuiltInFunction) visit(ctx.singleArgFunc()), (Expression) visit(ctx.factor()));
            case CHAR_TO_NUM: return new CharToNumFunc(ctx, (Expression) visit(ctx.factor()));
            case VALUE: return new ValueFunc(ctx, (Expression) visit(ctx.factor()));
            case LENGTH: return new NumberOfFunc(ctx, Countable.CHAR, (Expression) visit(ctx.factor()));
            case DISK_SPACE: return new DiskSpaceFunc(ctx, (Expression) visit(ctx.factor()));
            case PARAM: return new ParamFunc(ctx, (Expression) visit(ctx.factor()));

            default: throw new RuntimeException("Bug! Unimplemented one-arg function: " + ctx.singleArgFunc().getText());
        }
    }

    @Override
    public Object visitBuiltinFuncNoArg(HyperTalkParser.BuiltinFuncNoArgContext ctx) {
        switch ((BuiltInFunction) visit(ctx.zeroArgFunc())) {
            case MOUSE: return new MouseFunc(ctx);
            case MOUSELOC: return new MouseLocFunc(ctx);
            case RESULT: return new ResultFunc(ctx);
            case TICKS: return new TicksFunc(ctx);
            case SECONDS: return new SecondsFunc(ctx);
            case ABBREV_DATE: return new DateFunc(ctx, DateLength.ABBREVIATED);
            case SHORT_DATE: return new DateFunc(ctx, DateLength.SHORT);
            case LONG_DATE: return new DateFunc(ctx, DateLength.LONG);
            case ABBREV_TIME: return new TimeFunc(ctx, DateLength.ABBREVIATED);
            case LONG_TIME: return new TimeFunc(ctx, DateLength.LONG);
            case SHORT_TIME: return new TimeFunc(ctx, DateLength.SHORT);
            case OPTION_KEY: return new ModifierKeyFunc(ctx, ModifierKey.OPTION);
            case COMMAND_KEY: return new ModifierKeyFunc(ctx, ModifierKey.COMMAND);
            case SHIFT_KEY: return new ModifierKeyFunc(ctx, ModifierKey.SHIFT);
            case TOOL: return new ToolFunc(ctx);
            case NUMBER_CARD_PARTS: return new NumberOfFunc(ctx, Countable.CARD_PARTS);
            case NUMBER_BKGND_PARTS: return new NumberOfFunc(ctx, Countable.BKGND_PARTS);
            case NUMBER_CARD_BUTTONS: return new NumberOfFunc(ctx, Countable.CARD_BUTTONS);
            case NUMBER_BKGND_BUTTONS: return new NumberOfFunc(ctx, Countable.BKGND_BUTTONS);
            case NUMBER_CARD_FIELDS: return new NumberOfFunc(ctx, Countable.CARD_FIELDS);
            case NUMBER_BKGND_FIELDS: return new NumberOfFunc(ctx, Countable.BKGND_FIELDS);
            case NUMBER_MENUS: return new NumberOfFunc(ctx, Countable.MENUS);
            case NUMBER_CARDS: return new NumberOfFunc(ctx, Countable.CARDS);
            case NUMBER_MARKED_CARDS: return new NumberOfFunc(ctx, Countable.MARKED_CARDS);
            case NUMBER_BKGNDS: return new NumberOfFunc(ctx, Countable.BKGNDS);
            case MENUS: return new MenusFunc(ctx);
            case DISK_SPACE: return new DiskSpaceFunc(ctx);
            case PARAM_COUNT: return new ParamCountFunc(ctx);
            case PARAMS: return new ParamsFunc(ctx);
            case PROPERTY_DELEGATED: return new PropertyDelegatedFunc(ctx, ctx.zeroArgFunc().getText());

            default: throw new RuntimeException("Bug! Unimplemented no-arg function: " + ctx.zeroArgFunc().getText());
        }
    }

    @Override
    public Object visitBuiltinFuncArgList(HyperTalkParser.BuiltinFuncArgListContext ctx) {
        switch ((BuiltInFunction) visit(ctx.multiArgFunc())) {
            case MIN: return new MinFunc(ctx, (ExpressionList) visit(ctx.argumentList()));
            case MAX: return new MaxFunc(ctx, (ExpressionList) visit(ctx.argumentList()));
            case SUM: return new SumFunc(ctx, (ExpressionList) visit(ctx.argumentList()));
            case AVERAGE: return new AverageFunc(ctx, (ExpressionList) visit(ctx.argumentList()));
            case RANDOM: return new RandomFunc(ctx, (ExpressionList) visit(ctx.argumentList()));
            case ANNUITY: return new AnnuityFunc(ctx, (ExpressionList) visit(ctx.argumentList()));
            case COMPOUND: return new CompoundFunc(ctx, (ExpressionList) visit(ctx.argumentList()));
            case OFFSET: return new OffsetFunc(ctx, (ExpressionList) visit(ctx.argumentList()));
            default: throw new RuntimeException("Bug! Unimplemented arg-list function: " + ctx.multiArgFunc().getText());
        }
    }

    @Override
    public Object visitOneArgArgFunc(HyperTalkParser.OneArgArgFuncContext ctx) {
        return visit(ctx.singleArgFunc());
    }

    @Override
    public Object visitAnnuityArgFunc(HyperTalkParser.AnnuityArgFuncContext ctx) {
        return BuiltInFunction.ANNUITY;
    }

    @Override
    public Object visitCompoundArgFunc(HyperTalkParser.CompoundArgFuncContext ctx) {
        return BuiltInFunction.COMPOUND;
    }

    @Override
    public Object visitOffsetArgFunc(HyperTalkParser.OffsetArgFuncContext ctx) {
        return BuiltInFunction.OFFSET;
    }

    @Override
    public Object visitAverageFunc(HyperTalkParser.AverageFuncContext ctx) {
        return BuiltInFunction.AVERAGE;
    }

    @Override
    public Object visitMinFunc(HyperTalkParser.MinFuncContext ctx) {
        return BuiltInFunction.MIN;
    }

    @Override
    public Object visitMaxFunc(HyperTalkParser.MaxFuncContext ctx) {
        return BuiltInFunction.MAX;
    }

    @Override
    public Object visitSumFunc(HyperTalkParser.SumFuncContext ctx) {
        return BuiltInFunction.SUM;
    }

    @Override
    public Object visitNumberOfCardButtons(HyperTalkParser.NumberOfCardButtonsContext ctx) {
        return BuiltInFunction.NUMBER_CARD_BUTTONS;
    }

    @Override
    public Object visitNumberOfBkgndButtons(HyperTalkParser.NumberOfBkgndButtonsContext ctx) {
        return BuiltInFunction.NUMBER_BKGND_BUTTONS;
    }

    @Override
    public Object visitNumberOfCardFields(HyperTalkParser.NumberOfCardFieldsContext ctx) {
        return BuiltInFunction.NUMBER_CARD_FIELDS;
    }

    @Override
    public Object visitNumberOfBkgndFields(HyperTalkParser.NumberOfBkgndFieldsContext ctx) {
        return BuiltInFunction.NUMBER_BKGND_FIELDS;
    }

    @Override
    public Object visitMenusFunc(HyperTalkParser.MenusFuncContext ctx) {
        return BuiltInFunction.MENUS;
    }

    @Override
    public Object visitConstantExp(HyperTalkParser.ConstantExpContext ctx) {
        return super.visitConstantExp(ctx);
    }

    @Override
    public Object visitLiteralExp(HyperTalkParser.LiteralExpContext ctx) {
        String literal = ctx.getText();

        // Drop quotes from quoted string literal when converting a value
        if (literal.startsWith("\"") && literal.endsWith("\"")) {
            return new Value(String.valueOf(literal.substring(1, literal.length() - 1)));
        }

        return new Value(ctx.getText());
    }

    @Override
    public Object visitDiskSpaceNoArgFunc(HyperTalkParser.DiskSpaceNoArgFuncContext ctx) {
        return BuiltInFunction.DISK_SPACE;
    }

    @Override
    public Object visitParamsFunc(HyperTalkParser.ParamsFuncContext ctx) {
        return BuiltInFunction.PARAMS;
    }

    @Override
    public Object visitParamCountFunc(HyperTalkParser.ParamCountFuncContext ctx) {
        return BuiltInFunction.PARAM_COUNT;
    }

    @Override
    public Object visitPropDelegatedFunc(HyperTalkParser.PropDelegatedFuncContext ctx) {
        return BuiltInFunction.PROPERTY_DELEGATED;
    }

    @Override
    public Object visitLongTimeFormat(HyperTalkParser.LongTimeFormatContext ctx) {
        return DateLength.LONG;
    }

    @Override
    public Object visitAbbreviatedTimeFormat(HyperTalkParser.AbbreviatedTimeFormatContext ctx) {
        return DateLength.ABBREVIATED;
    }

    @Override
    public Object visitShortTimeFormat(HyperTalkParser.ShortTimeFormatContext ctx) {
        return DateLength.SHORT;
    }

    @Override
    public Object visitDefaultTimeFormat(HyperTalkParser.DefaultTimeFormatContext ctx) {
        return DateLength.DEFAULT;
    }

    @Override
    public Object visitDiskSpaceFunc(HyperTalkParser.DiskSpaceFuncContext ctx) {
        return BuiltInFunction.DISK_SPACE;
    }

    @Override
    public Object visitParamFunc(HyperTalkParser.ParamFuncContext ctx) {
        return BuiltInFunction.PARAM;
    }

    @Override
    public Object visitNumberOfCardParts(HyperTalkParser.NumberOfCardPartsContext ctx) {
        return BuiltInFunction.NUMBER_CARD_PARTS;
    }

    @Override
    public Object visitNumberOfBkgndParts(HyperTalkParser.NumberOfBkgndPartsContext ctx) {
        return BuiltInFunction.NUMBER_BKGND_PARTS;
    }

    @Override
    public Object visitNumberOfCharsFunc(HyperTalkParser.NumberOfCharsFuncContext ctx) {
        return BuiltInFunction.NUMBER_CHARS;
    }

    @Override
    public Object visitNumberOfWordsFunc(HyperTalkParser.NumberOfWordsFuncContext ctx) {
        return BuiltInFunction.NUMBER_WORDS;
    }

    @Override
    public Object visitNumberOfItemsFunc(HyperTalkParser.NumberOfItemsFuncContext ctx) {
        return BuiltInFunction.NUMBER_ITEMS;
    }

    @Override
    public Object visitNumberOfLinesFunc(HyperTalkParser.NumberOfLinesFuncContext ctx) {
        return BuiltInFunction.NUMBER_LINES;
    }

    @Override
    public Object visitNumberOfMenuItemsFunc(HyperTalkParser.NumberOfMenuItemsFuncContext ctx) {
        return BuiltInFunction.NUMBER_MENUITEMS;
    }

    @Override
    public Object visitNumberOfBkgndCardsFunc(HyperTalkParser.NumberOfBkgndCardsFuncContext ctx) {
        return BuiltInFunction.NUMBER_BKGND_CARDS;
    }

    @Override
    public Object visitNumberOfMenusFunc(HyperTalkParser.NumberOfMenusFuncContext ctx) {
        return BuiltInFunction.NUMBER_MENUS;
    }

    @Override
    public Object visitNumberOfCardsFunc(HyperTalkParser.NumberOfCardsFuncContext ctx) {
        return BuiltInFunction.NUMBER_CARDS;
    }

    @Override
    public Object visitNumberOfMarkedCards(HyperTalkParser.NumberOfMarkedCardsContext ctx) {
        return BuiltInFunction.NUMBER_MARKED_CARDS;
    }

    @Override
    public Object visitNumberOfBackgrounds(HyperTalkParser.NumberOfBackgroundsContext ctx) {
        return BuiltInFunction.NUMBER_BKGNDS;
    }

    @Override
    public Object visitRandomFunc(HyperTalkParser.RandomFuncContext ctx) {
        return BuiltInFunction.RANDOM;
    }

    @Override
    public Object visitSqrtFunc(HyperTalkParser.SqrtFuncContext ctx) {
        return BuiltInFunction.SQRT;
    }

    @Override
    public Object visitSinFunc(HyperTalkParser.SinFuncContext ctx) {
        return BuiltInFunction.SIN;
    }

    @Override
    public Object visitCosFunc(HyperTalkParser.CosFuncContext ctx) {
        return BuiltInFunction.COS;
    }

    @Override
    public Object visitTanFunc(HyperTalkParser.TanFuncContext ctx) {
        return BuiltInFunction.TAN;
    }

    @Override
    public Object visitAtanFunc(HyperTalkParser.AtanFuncContext ctx) {
        return BuiltInFunction.ATAN;
    }

    @Override
    public Object visitExpFunc(HyperTalkParser.ExpFuncContext ctx) {
        return BuiltInFunction.EXP;
    }

    @Override
    public Object visitExp1Func(HyperTalkParser.Exp1FuncContext ctx) {
        return BuiltInFunction.EXP1;
    }

    @Override
    public Object visitExp2Func(HyperTalkParser.Exp2FuncContext ctx) {
        return BuiltInFunction.EXP2;
    }

    @Override
    public Object visitLnFunc(HyperTalkParser.LnFuncContext ctx) {
        return BuiltInFunction.LN;
    }

    @Override
    public Object visitLn1Func(HyperTalkParser.Ln1FuncContext ctx) {
        return BuiltInFunction.LN1;
    }

    @Override
    public Object visitLog2Func(HyperTalkParser.Log2FuncContext ctx) {
        return BuiltInFunction.LOG2;
    }

    @Override
    public Object visitNumToCharFunc(HyperTalkParser.NumToCharFuncContext ctx) {
        return BuiltInFunction.NUM_TO_CHAR;
    }

    @Override
    public Object visitValueFunc(HyperTalkParser.ValueFuncContext ctx) {
        return BuiltInFunction.VALUE;
    }

    @Override
    public Object visitLengthFunc(HyperTalkParser.LengthFuncContext ctx) {
        return BuiltInFunction.LENGTH;
    }

    @Override
    public Object visitCharToNumFunc(HyperTalkParser.CharToNumFuncContext ctx) {
        return BuiltInFunction.CHAR_TO_NUM;
    }

    @Override
    public Object visitAbsFunc(HyperTalkParser.AbsFuncContext ctx) {
        return BuiltInFunction.ABS;
    }

    @Override
    public Object visitTerminal(TerminalNode node) {
        return node.getText();
    }
}
