package com.defano.hypertalk.ast.common;

public enum VisualEffectName {
    DISSOLVE,
    BARN_DOOR_OPEN,
    BARN_DOOR_CLOSE,
    CHECKERBOARD,
    IRIS_OPEN,
    IRIS_CLOSE,
    PLAIN,
    SCROLL_DOWN,
    SCROLL_UP,
    SCROLL_LEFT,
    SCROLL_RIGHT,
    SHRINK_TO_TOP,
    SHRING_TO_CENTER,
    SHRINK_TO_BOTTOM,
    STRETCH_FROM_TOP,
    STRETCH_FROM_CENTER,
    STRETCH_FROM_BOTTOM,
    VENETIAN_BLINDS,
    WIPE_UP,
    WIPE_DOWN,
    WIPE_LEFT,
    WIPE_RIGHT,
    ZOOM_IN,
    ZOOM_OUT
}
